### ISSUE TITLE
Avoid generating and reverifying blocks

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#1002]
### Expected Behavior

Validators should only verify blocks they have not seen before, and avoid creating new blocks unless they are likely to propose them. 

### Current Behavior

Validators process each block usually 3 times: once through worker.go, then usually we’re not the proposer so we throw it away. Then, the second time when we receive a PREPREPARE (then we cache the result so we don’t re-verify). Then finally a block gets committed and we receive it via newChainHead, and verify it again (even though we likely already verified it).

Share the verify cache outside of istanbul, and use consensus to drive when we produce a block in worker.go — not the other way round

**Comment by YoduYodu** [comment]
TODO: Clarify if `verify cache outside of istanbul`

**Comment by kevjue** [comment]
This is a dup of #1253
