### ISSUE TITLE
Non-validating nodes with locked etherbase will max out CPU in the ethstats loop

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1003]
If a node specifies an etherbase, but does not unlock it, and tries to report to ethstats the goroutine that reports stats falls into a loop of checking the unlock status of the account with no delay, maxing out the CPU.

https://github.com/celo-org/celo-blockchain/blob/15d280e12fb720b7e82d69d2862f7684444fdb67/ethstats/ethstats.go#L268

**Comment by H34D** [comment]
this might fix it: https://github.com/celo-org/celo-blockchain/pull/974

**Comment by nategraf** [comment]
This issue no longer exists on `master`
