### ISSUE TITLE
BLS signing delays longer than expected

### ISSUE THREAD

**Issue by mstraka100** [celo-org/celo-blockchain#1005]
### Expected Behavior

When running a 100-validator network with a BLS signing delay, blocktimes will not increase significantly more than the length of this delay

### Current Behavior

When running a 100-validator network with a 2-second BLS signing delay and 5s targeted blocktimes, every 20-30 blocks will show a blocktime of ~1 minute. It is possible but rare for blocks to take between 12 and 50 seconds. Occasionally, a block `n+1` taking ~12 seconds will occur immediately after a block `n` taking ~60 seconds.

This behavior does not occur consistently, as the network will over some periods of time have no delays while achieving 5s blocktimes. This is always the case with 10 validators and a 2-second signing delay.

Similar behavior has been observed with:

- an otherwise identical 100-validator testnet with a 0.7s signing delay
- an otherwise identical 100-validator testnet with a 2s signing delay, which each validator at startup has a 50% chance of being assigned. This is to simulate 50% of validators using a ledger wallet for BLS signatures

Both of the above networks result in less frequent and less severe delays on average, but not always.

### Steps to Reproduce Behavior

Run a testnet with 100 validators, blocktime 5 seconds, and timeout of 3000ms, on this commit: https://github.com/celo-org/celo-blockchain/commit/ee29b2ef583a6a1c581050204e8bc6a71ede2db0

### Logs

This issue appears to occur at the same time as the error described here: https://github.com/celo-org/celo-blockchain/issues/1004

### System information

```Celo
Version: 0.10.0-unstable
Git Commit: ee29b2ef583a6a1c581050204e8bc6a71ede2db0
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.6
Operating System: darwin
GOPATH=
GOROOT=/usr/local/go```

**Comment by nategraf** [comment]
@trianglesphere do you think is related to the round change behavior you've been reseaching?

**Comment by trianglesphere** [comment]
Depending on the load, this could cause a cascading failure through the first couple rounds, but I suspect that is also has something to do with the `inconsistent PREPARE` that is seen when this occurs. I've actually seen that message on baklava once or twice, but wasn't able to track down which node it came from. I think that issue is more likely to result in timeouts and round changes.

**Comment by trianglesphere** [comment]
I believe that is a combination of non-exponential early round changes (to be fixed) and the inconsistent prepare bug (fixed)
