### ISSUE TITLE
Make BLS signing done in separate thread

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#1020]
### Expected Behavior

The BLS signing should be done in separate thread.

### Current Behavior

Currently, the BLS signing is done within the single threaded istanbul core engine.  Since it's expected that BLS signing can take about 1 second, the signing essentially freezes the core engine, causing round changes in the subsequent sequence.  See https://github.com/celo-org/celo-blockchain/issues/1005 for more details.

### Steps to Reproduce Behavior

See https://github.com/celo-org/celo-blockchain/issues/1005

**Comment by mrsmkl** [comment]
Here are my current thoughts:
BLS signing is done for the commit message. So when this message is going to be sent, a new worker can be started to avoid blocking (probably not a new worker, it's better to have one thread for handling this because it's sequential in the Ledger anyway). The main thread will consider the message as sent (this is the reason why it's still secure).
Note that there are two signatures required.
I'll check if the signing requests can be posted optimistically to save time.

**Comment by kevjue** [comment]
> Here are my current thoughts:
> BLS signing is done for the commit message. So when this message is going to be sent, a new worker can be started to avoid blocking (probably not a new worker, it's better to have one thread for handling this because it's sequential in the Ledger anyway). The main thread will consider the message as sent (this is the reason why it's still secure).
> Note that in epoch blocks, there are two signatures required.
> 
> Perhaps the signing requests can be posted optimistically to save time.

IIUC, your proposal will have a single threaded "BLS Signer and commit message sender" worker thread, and that the main consensus thread will delegate those tasks to the worker (And I presume that this worker will know to reprioritize jobs based on incoming jobs' view number?).

In the meantime, the main consensus thread will transition to "COMMITTED" state, assuming that the message is sent.

If my understanding is correct, then I think that makes sense.  The consensus algorithm already has to deal with messages that are lost over the wire, so you could encompass those lost events with "lost" events in the worker thread.  One optimization to consider in the future (perhaps even now if it's not hard to do) is to have your worker thread persist its state.  E.g. if the client crashes before sending the message, the worker thread will then know where to pick up.

Also, one thing that you may want to put some thought into is when you reprioritize these jobs, how does that affect the "message sent" assumption that the main thread is making.
