### ISSUE TITLE
Treat oracle transactions as “local” txs

### ISSUE THREAD

**Issue by pranaymohan** [celo-org/celo-blockchain#1023]
### Expected Behavior

Treat oracle transactions as “local” to prioritize oracle reports in periods of high traffic, so that they get mined and included in blocks

### Current Behavior

Oracle txns do not have priority over regular transactions

### Steps to Reproduce Behavior

N/A

### Logs

N/A

### System information

N/A

**Comment by mcortesi** [comment]
We don't need this for now. Closing for the moment
