### ISSUE TITLE
Dutch Auction clearing-price instead of First-price for Fees

### ISSUE THREAD

**Issue by joigno** [celo-org/celo-blockchain#1030]
### Expected Behavior

Base Fees, also know as Minimum Gas Price, decided by an algorithm (EIP1599) or by block proposers (RSK09) is an interesting technique to protect block proposers profit during low tx volume scenarios, and also to protect from Bribing Attacks. Is not clear how this technique helps users sending transactions during peak congestion times where fees usually skyrocket because _they are charged exactly their bid._.

We propose maintaining the Base Fee alternative but implementing a classic Dutch Auction for each block to be proposed, so instead of being _charged exactly their bid._ they are charged an unique clearing price same or above de Base Fee so peak prices are avoided during congested times. This can be specially good to allow High Priority 

### Current Behaviour

Base Tx fee is computed in base of EIP1599, but still might suffer peak prices during peak tx volume times. This will hurt High Urgency users sending Txs or High Priority, possibly like official SortedOracles txs.

### Analogy with CoinList Dutch Auctions

![image](https://user-images.githubusercontent.com/30682875/81326397-0f0b8d00-909a-11ea-8029-b9cf63812e5d.png)

### Example Skyrocket of Fees on Ethereum network during 2020

![image](https://user-images.githubusercontent.com/30682875/81326115-9d334380-9099-11ea-99a9-df68bd1850a7.png)

**Comment by manfr3d** [comment]
Does this produce a perverse incentive to not include transactions for which there are space if they would lower the clearing price?

There is also a Minimum Price from EIP1599 that can be maintained, if the block is a percentage empty (lets say 5 or 10% empty), then the Minimum Price can be raised a small percentage like 1%.

**Comment by asaj** [comment]
If you're talking about EIP 1559, that is already implemented in the Celo protocol

**Comment by manfr3d** [comment]
I think is ortogonal, EIP-1559 is for dynamic Minimum Price, and what I am proposing is for type of Auction. Can be First-price, Second-Price, Dutch, etc.

**Comment by joigno** [comment]
People ranting about EIP-1559 -> https://www.reddit.com/r/ethereum/comments/fhkca3/eip_1559_when/

**Comment by joigno** [comment]
Blog post about EIP-1559: https://medium.com/@eric.conner/fixing-the-ethereum-fee-market-eip-1559-9109f1c1814b

**Comment by joigno** [comment]
Blog post with praises for eEIP-1559: https://medium.com/@TrustlessState/eip-1559-the-final-puzzle-piece-to-ethereums-monetary-policy-58802ab28a27

This doesn't look to me as a Feature:

> Burning BASEFEE removes the ability for validators to manipulate the fee market for their benefit. It also ‘locks-in’ Ether as the native currency of Ethereum, as it should be. No other currency on Ethereum can be used to pay for transactions. This is comparable to a nation-state demanding that only their native currency be legal tender.

**Comment by joigno** [comment]
The premium and the feecap are both chosen by the tx sender, I think it will still spiral into Price Spikes: GASPRICE = min(BASEFEE + tx.GasPremium, tx.fee_cap) (edited) 

What is fee cap?

feecap is the maximum BASEFEE + tx.GasPremium the sender is willing to pay, if BASEFEE grows to much the tx is not included in the block. Fee Price Spike are generated by congestion and auction mechanism not by miners incrementing min gas price.
