### ISSUE TITLE
Celo blockchain client periodically disconnects from peer with "retrieved hash chain is invalid" error

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#1051]
### Expected Behavior

Celo blockchain client should not disconnect from peer with "retrieved hash chain is invalid" error when the peer has the correct blockchain.

### Current Behavior

Celo blockchain client periodically disconnects from peer with "retrieved hash chain is invalid" error even when the peer has the correct blockchain.

### Steps to Reproduce Behavior

This error is currently happening on cLab's validator-0 on the alfajores network (As of June 2, 2020).  Note that this network will be reset soon.

### Logs

Here is a sequence of logs that will show the node attempting to sync from a peer, and then encountering and error and disconnecting from the peer:

https://console.cloud.google.com/logs/viewer?interval=NO_LIMIT&project=celo-testnet-production&authuser=0&minLogLevel=0&expandAll=false&customFacets&limitCustomFacetWidth=true&scrollTimestamp=2020-06-03T00%3A14%3A35.105086507Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22alfajores%22%0Aresource.labels.namespace_id%3D%22alfajores%22%0Aresource.labels.project_id%3D%22celo-testnet-production%22%0Aresource.labels.zone%3A%22us-west1-a%22%0Aresource.labels.container_name%3D(%22init-genesis%22%20OR%20%22get-account%22%20OR%20%22import-geth-account%22%20OR%20%22geth%22%20OR%20%22geth-exporter%22%20OR%20%22prom-to-sd%22)%0Aresource.labels.pod_id%3D%22alfajores-validators-0%22%0Atimestamp%3E%3D%222020-06-03T00%3A14%3A35.096084325Z%22%0Atimestamp%3C%3D%222020-06-03T00%3A14%3A40.202686794Z%22

### System information

/ # geth version
Celo
Version: 1.0.0-unstable
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

**Comment by kevjue** [comment]
I tried downloading the data dir from alfajores validator 0, and running a full node on my local computer with that datadir, and my local full node was able to sync fine.

My local full node's sync related logs is significantly different than the stackdriver logs posted in the issue's description.  Here are my local full node's sync related logs:

```
DEBUG[06-02|17:21:44.967] Synchronising with the network           peer=2ef4d3aec48f17d3                 eth=65 head=b2b7e9…22e08a td=883699 mode=full
DEBUG[06-02|17:21:44.967] Current head is 198044
DEBUG[06-02|17:21:44.967] Retrieving remote chain height           peer=2ef4d3aec48f17d3
DEBUG[06-02|17:21:44.967] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1 fromhash=b2b7e9…22e08a skip=0 reverse=false
TRACE[06-02|17:21:44.999] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:44.999] Remote head header identified            peer=2ef4d3aec48f17d3                 number=883698 hash=b2b7e9…22e08a
DEBUG[06-02|17:21:44.999] Looking for common ancestor              peer=2ef4d3aec48f17d3                 local=198044 remote=883698
TRACE[06-02|17:21:44.999] Span searching for common ancestor       peer=2ef4d3aec48f17d3                 count=12 from=883521 skip=15
DEBUG[06-02|17:21:44.999] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=12 fromnum=883521 skip=15 reverse=false
TRACE[06-02|17:21:45.030] Binary searching for common ancestor     peer=2ef4d3aec48f17d3                 start=108044 end=883698
DEBUG[06-02|17:21:45.030] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=495871 skip=0  reverse=false
TRACE[06-02|17:21:45.076] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:45.077] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=301957 skip=0  reverse=false
TRACE[06-02|17:21:45.117] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:45.117] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=205000 skip=0  reverse=false
TRACE[06-02|17:21:45.162] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:45.162] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=156522 skip=0  reverse=false
TRACE[06-02|17:21:45.199] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:45.200] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=180761 skip=0  reverse=false
TRACE[06-02|17:21:45.242] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:45.243] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=192880 skip=0  reverse=false
TRACE[06-02|17:21:45.282] Filtering headers                        peer=2ef4d3aec48f17d3                 headers=1
DEBUG[06-02|17:21:45.283] Fetching batch of headers                id=2ef4d3aec48f17d3 conn=staticdial count=1  fromnum=198940 skip=0  reverse=false
.
.
.
```

**Comment by kevjue** [comment]
Here's the steps to run a local full node mentioned in the previous comments.

1. Download the datadir:  https://drive.google.com/file/d/10EZSYYqfo3741E4zZEYhcIssGp3uFQY4/view?usp=sharing
2. Run geth with the command `./geth --datadir ~/celo.back --networkid=44786 --istanbul.blockperiod=5 --istanbul.requesttimeout=10000 --maxpeers=125  --use-in-memory-discovery-table --syncmode=full --verbosity=5`
3. Attach the running geth instance
4. Within the geth attach, run `admin.addPeer("enode://02d18a52c4e097c12412ac3da9a9af24745cff182306e21fb1d3d691fe0c25f65c60586302b933bb9ec300b7fb00ed719d26a4d57af91d447691bac2b2d778af@34.83.107.15:30303")`

**Comment by kevjue** [comment]
One other clue that I discovered is that it appears that alfajores's val-0 blockchain blockcache has entries that are greater than it's current head block on disk (which is 198044).  So the `hasBlock` function does return true in some cases when in fact it's not true:  https://github.com/celo-org/celo-blockchain/blob/master/core/blockchain.go#L695.

This inconsistency ultimately leads to the "retrieved hash chain is invalid" error.

**Comment by kevjue** [comment]
The inconsistency between the in memory cache and the on disk blockchain seems to be manifesting itself on tx-node 3 on alfajoresstaging testnet (as of June 4th, 2020).  That node is continuously seg faulting on this line:  https://github.com/celo-org/celo-blockchain/blob/master/eth/downloader/downloader.go#L910 with the following traceback:


```
goroutine 308 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0xc001ca1a40, 0xc002c28780, 0xc001dcab40, 0x0, 0x0, 0xa)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:910 +0x1454
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0xc001ca1a40, 0xc002c28780, 0xff2a4bbccb38a847, 0xf50c645e3a1c2de7, 0xf1636a3d8a498a42, 0x98eb058a34441964, 0xc003397980, 0x0, 0x0)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:472 +0x3f0
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0xc001ca1a40, 0xc002bdbe80, 0x10, 0xff2a4bbccb38a847, 0xf50c645e3a1c2de7, 0xf1636a3d8a498a42, 0x98eb058a34441964, 0xc003397980, 0x0, 0x0, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:440 +0x3c3
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0xc001ca1a40, 0xc002bdbe80, 0x10, 0xff2a4bbccb38a847, 0xf50c645e3a1c2de7, 0xf1636a3d8a498a42, 0x98eb058a34441964, 0xc003397980, 0x0, 0xc002db2fe8, ...)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:352 +0x8e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0xc000318c00, 0xc0032f4000)
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:190 +0x2dd
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
	/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:151 +0x2b7
```

**Comment by mrsmkl** [comment]
Here's what it looks to me happened with validator 0
* April 21th there was a restart, block number was around 198044. The chain was probably corrupted then
* May 31st the alfajores network was down, also validator 0 was restarted. Genesis block was rewritten, not sure if that impacted anything
* DB corruption was detected and the new head was 198044. Previous head was 852228
* All the frozen blocks above head were removed 198045-762228 (after 90000 confirmations, the blocks are frozen)
* At least the block headers above 762228 remained in the DB
* When starting sync, the validator found a new (>762228) common block with the peer
* It loaded the blocks and inserted them into sidechain
* Returned the error because 762228 didn't have an ancestor

Why it was different when it was started from copied datadir (theory)
* Some time had passed, it didn't find the common ancestor with span search anymore
* Used bisection, found 198044

Suggested fix
* When an orphaned sidechain is found, remove it

**Comment by kevjue** [comment]
> * DB corruption was detected and the new head was 198044. Previous head was 852228
> * All the frozen blocks above head were removed 198045-762228 (after 90000 confirmations, the blocks are frozen)

IIUC, your suggested fix is that when DB corruption is detected and the head is set to a previous block, that in addition to the removal of the frozen block, that all the headers > the new head is also removed?  If so, that makes sense to me.
