### ISSUE TITLE
Fix fast sync

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#1059]
### Expected Behavior

Fast sync should not encounter a bad block error.

### Current Behavior

If a blockchain is longer than an epoch long, then when a node syncs from the genesis block, it will encounter a BAD BLOCK error when syncing an epoch block.

### Steps to Reproduce Behavior

Running fast sync from the genesis block on any network with chain length > an epoch length should work.

### Logs

Here's a slack thread that includes logs:  https://celo-org.slack.com/archives/C9RSRC8KS/p1589742764366400

### System information

Run `geth version`

**Comment by mrsmkl** [comment]
Couldn't reproduce, can you post the logs from slack?

**Comment by mrsmkl** [comment]
Here's a related PR with more information https://github.com/celo-org/celo-blockchain/pull/1041
Was now able to reproduce with info from that PR, looks like uptimes aren't updated when doing fast sync.
