### ISSUE TITLE
--dev flag throws seg fault 

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-blockchain#1063]
### Expected Behavior

Starting upstream (i.e. Ethereum's ) geth with --dev flag would normally start up a local network with the clique consensus engine. Since we no longer have clique in celo-blockchain, using --dev throws a seg fault. Expected behavior would be for --dev to start up succesfully with istanbul. 

### Current Behavior

--dev seg faults because the genesis block it uses is incompatible with istanbul (see DeveloperGenesisBlock in genesis.go). We've received feedback from an external partner that adding back an istanbul compatible version of dev mode would be very helpful. 

### Steps to Reproduce Behavior

`geth --dev --nodiscover --maxpeers 0 --light.maxpeers 0 --mine --minerthreads 1 --datadir /data --verbosity 3 --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net --nousb`

### Logs

`WARN [05-30|00:20:29.778] Error getting snapshot                   number=0 hash=c98bf6…d25f28 err="rlp: expected input list for struct { AddedValidators []common.Address; AddedValidatorsPublicKeys []blscrypto.SerializedPublicKey; RemovedValidators *big.Int; Seal []uint8; AggregatedSeal types.IstanbulAggregatedSeal; ParentAggregatedSeal types.IstanbulAggregatedSeal }"
ERROR[05-30|00:20:29.779] Unable to extract istanbul extra         err="rlp: expected input list for struct { AddedValidators []common.Address; AddedValidatorsPublicKeys []blscrypto.SerializedPublicKey; RemovedValidators *big.Int; Seal []uint8; AggregatedSeal types.IstanbulAggregatedSeal; ParentAggregatedSeal types.IstanbulAggregatedSeal }"
WARN [05-30|00:20:29.779] Error getting snapshot                   number=0 hash=c98bf6…d25f28 err="rlp: expected input list for struct { AddedValidators []common.Address; AddedValidatorsPublicKeys []blscrypto.SerializedPublicKey; RemovedValidators *big.Int; Seal []uint8; AggregatedSeal types.IstanbulAggregatedSeal; ParentAggregatedSeal types.IstanbulAggregatedSeal }"
INFO [05-30|00:20:29.779] Commit new mining work                   number=1 sealhash=197825…04291d txs=0 gas=0 fees=0 elapsed=294.459µs
ERROR[05-30|00:20:29.779] Unable to extract istanbul extra         err="rlp: expected input list for struct { AddedValidators []common.Address; AddedValidatorsPublicKeys []blscrypto.SerializedPublicKey; RemovedValidators *big.Int; Seal []uint8; AggregatedSeal types.IstanbulAggregatedSeal; ParentAggregatedSeal types.IstanbulAggregatedSeal }"
WARN [05-30|00:20:29.779] Block sealing failed                     err="rlp: expected input list for struct { AddedValidators []common.Address; AddedValidatorsPublicKeys []blscrypto.SerializedPublicKey; RemovedValidators *big.Int; Seal []uint8; AggregatedSeal types.IstanbulAggregatedSeal; ParentAggregatedSeal types.IstanbulAggregatedSeal }"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc98620]

goroutine 252 [running]:
github.com/ethereum/go-ethereum/consensus/istanbul/core.(*roundStateImpl).EncodeRLP(0xc000bb4100, 0x1882100, 0xc000c3c050, 0x0, 0x0)
    /opt/testnet-celo-blockchain/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/core/roundstate.go:528 +0x100
github.com/ethereum/go-ethereum/rlp.makeEncoderWriter.func2(0x15bd9c0, 0xc000bb4100, 0x199, 0xc000c3c050, 0xc000bb4100, 0x199)
    /opt/testnet-celo-blockchain/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:541 +0x15a
github.com/ethereum/go-ethereum/rlp.makePtrWriter.func1(0x15c71e0, 0xc000bb4100, 0x16, 0xc000c3c050, 0x15c0000, 0xc000b9e060)
    /opt/testnet-celo-blockchain/build/_workspace/src/github.com/ethereum/go-ethereum/rlp/encode.go:523 +0xba
github.com/ethereum/go-ethereum/rlp.(*encbuf).encode(0xc000c3c050, 0x15c71e0, 0xc000bb4100, 0x4b222c, 0x20)`

### System information

Run `geth version`

**Comment by kevjue** [comment]
@alecps - We don't have the clique consensus engine anymore in our version of geth.

**Comment by alecps** [comment]
@kevjue  Apologies, I think my explanation was unclear (hopefully better now). The issue is that we no longer have clique, so dev mode should either work with istanbul or be removed.
