### ISSUE TITLE
Users SBAT pay a predictable fee

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#107]
Inspired by previous conversations and discussion of http://hackingdistributed.com/2019/01/22/doing-fees-right/ ---
* Update size of block (maybe low water mark [below which gasprice=0], high water mark [above which all gasprice='low water' transaction gasprice])
* Modify GPO to always return average of (lowest fee in last B blocks, or free if empty)
* Change block creation logic to set/check fee appropriately

**Comment by jarmg** [comment]
Done:
https://github.com/celo-org/celo-blockchain/pull/248
