### ISSUE TITLE
Copy docs from geth (gh-pages branch)

### ISSUE THREAD

**Issue by bowd** [celo-org/celo-blockchain#1072]
### Summary

As part of our [Release Process Documentation](https://github.com/celo-org/celo-monorepo/pull/4045) we decided to surface geth docs in the `celo-blockchain` repo. Geth hosts the docs on github and therefore they are only found in the `gh-pages` branch, and not on `master`. We're thinking of moving them, as is, to the `master` branch.

### Issues with the approach

Making this structural change to the repo will increase complexity when merging upstream geth. Especially if upstream geth makes changes to the docs `gh-pages`, and we have also made changes to our `docs` on master, these will no longer share a common git history that's mergeable (unless we do some fancy git-work, which I'm not totally sure is possible).

Secondly, the docs are constructed as a `jekyll` static site that builds to what you see [here](https://geth.ethereum.org/) and they are constructed to best serve that purpose. Which means that folders don't have a `README.md` which would render in github and that the various links in the markdown files don't work, they are designed to work only when the site is built.

If we include instruction on how to build the static site (which requires installing ruby and a whole bunch of gems) I think it makes more sense to host it ourselves anyway.

Then there's also the question of how much of the content we need to massage. Currently it includes a release page with links to geth binaries and things like that.

### Alternative approach

I would suggest we keep the `gh-pages` way of doing things but we spend some time editing the static site to include branding and remove things like links to geth binaries. We then link to this page when needed.

We should update the docs to reflect differences between `geth` and the `celo-blockchain` client and make sure to keep it up to date when merging upstream geth.

### Initial approach

If we really want to surface these docs on the `master` branch I would:

- [ ] Copy over the docs folder to the `master` branch
- [ ] Edit slightly to remove the release page and introduce some branding
- [ ] Include instruction on how to build and view the docs

**Comment by nategraf** [comment]
Good observations! Really the goal here is simple to have the Geth documentation in our own source control so we can start editing it, and to make it easy to access. I would say that the method Geth uses does not do a great job of making the docs easy to find, which is evident from the fact that the easiest documentation to find for Geth are the "deprecated" wiki pages. That is why I proposed we move the docs to the `master` branch, but I did not look very far into how the docs are built. If you have a method that will work and allow us to have a fork of the Geth docs we can edit, and are discoverable, thenI'd say that's mission accomplished!
