### ISSUE TITLE
Validator fails to make connection to certain other validators causing it to miss signatures

### ISSUE THREAD

**Issue by tyrion70** [celo-org/celo-blockchain#1078]
### Expected Behavior

Each validator should be connected to all other validators

### Current Behavior

In some cases validators are not connected to some other validators

### Steps to Reproduce Behavior

No idea, it happens from time to time, and usually for a complete epoch

### Logs

```
Jun 14 13:11:32 prod-celo-validator1a geth[744]: INFO [06-14|13:11:32.331] Error sending all version certificates   func=RegisterPeer                  err="write tcp IP:30303->IP:PORT: use of closed network connection"
Jun 14 13:12:37 prod-celo-validator1a geth[744]: INFO [06-14|13:12:37.708] Error sending all version certificates   func=RegisterPeer                  err="shutting down"
Jun 14 13:12:37 prod-celo-validator1a geth[744]: INFO [06-14|13:12:37.703] Disconnecting from static or trusted peer id=b3ed97f60505f010 conn=trusted-inbound    static=ValidatorPurpose      trusted=ValidatorPurpose reason="too many peers"         remoteRequested=true  err="too many peers"
Jun 14 13:12:40 prod-celo-validator1a geth[744]: INFO [06-14|13:12:40.955] Disconnecting from static or trusted peer id=b3ed97f60505f010 conn=trusted-staticdial static=ValidatorPurpose      trusted=ValidatorPurpose reason="too many peers"         remoteRequested=true  err="too many peers"
```

it seems that the other validator does not trust the validator because something goes wrong when sending certificates. This them causes the other validator to drop the connection because it has too many peers.

### System information

```# geth version
Celo
Version: 1.0.0-stable
Git Commit: 8a44c2cd92200bdffce595c7558e84a39ea2bc15
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go```

**Comment by tyrion70** [comment]
Earlier we've tried to check the logging of the validators on "the other side" of these errors. They saw these errors on their logging:
```ERROR[05-25|04:55:26.210] Got a consensus message signed by a non validator.
INFO [05-25|04:55:26.210] Disconnecting from static or trusted peer id=6ee8d4b57ffdb359 conn=trusted-staticdial static=ValidatorPurpose trusted=ValidatorPurpose reason="useless peer"           remoteRequested=false err="useless peer"
```
Its kinda hard to coordinate with the validators to check this since it changes each epoch and it doesn't always occur, but it might be helpful to do a debug session between two validators that have this issue during an epoch?

**Comment by chris-remus** [comment]
Taken from [this Discord chat](https://discordapp.com/channels/600834479145353243/601046166620078100/722511498127343676) -

I'm still working to troubleshoot missed blocks and discovered a curious pattern.

For about 8-9 hrs I was missing every XXXX88 & XXXX89 block, now that pattern reset and I'm missing every XXXX45 & XXXX46 block. 

The blocks come from the same miner, e.g. XXXX88 from proposer A, XXXX89 from proposer B, then XXXX45 from miner C and XXXX46 from miner D.

Does anyone have an idea what might be causing this? It seems strange that I'd lose connectivity with different miner pairs on such a regular basis.

**Comment by nategraf** [comment]
I went back to 8a44c2cd92200bdffce595c7558e84a39ea2bc15 today and spent some time looking into this. @tyrion70 Your theory about a failure in the enode certificate handling logic seems reasonable, but is indeed not possible to confirm this without the logs from, in this the case, the remote validator's proxy.

Next steps on this will be to identify a pair of nodes likely experiencing this issue and contact them to get log. @YazzyYaz It would be helpful to have your support on this.
