### ISSUE TITLE
System contract calls should not fail

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-blockchain#1084]
### Expected Behavior

Contract calls made by the system should not fail.

### Current Behavior

Some system calls fail on the epoch boundary, causing the block to rejected and state to be reverted. `distributeEpochRewards` makes many contract calls as system. If any of them fail, the state is reverted. This is dangerous since unless a new tx comes into the mem pool that doesn't cause the call to fail, no new block will be produced.

### Steps to Reproduce Behavior

How can we reproduce this?
Observe logs on a full-node instance
ex. `kubectl logs baklava-fullnodes-0 -n baklava`

#### Mainnet Occurrence

> {"err":"evm: execution reverted","function":"updateValidatorScoreFromSigner","msg":"Error in executing function on registered contract","registryId":"0x49dc7107d41d3c01a9f941a7d9a9f9177349b5521aeb56861470e42cf05da2ee","severity":"error","timestamp":"2020-06-12T04:42:06.228455771Z"}
> {"blockNumber":"172800","err":"evm: execution reverted","msg":"Failed to distribute epoch rewards","severity":"error","timestamp":"2020-06-12T04:42:06.228531372Z"}

#### Baklava Occurrence

> {"err":"evm: execution reverted","function":"isReserveLow","msg":"Error in executing function on registered contract","registryId":"0xb33c3d77234979a288baf651b42d19d8483d5af3e328f9f1fae2bef7b11acd25","severity":"error","timestamp":"2020-06-26T17:54:38.387341998Z"}
> {"blockNumber":"34560","err":"evm: execution reverted","msg":"Failed to distribute epoch rewards","severity":"error","timestamp":"2020-06-26T17:54:38.387363198Z"}

**Comment by codyborn** [comment]
Chatted with @asaj and he believes that this doesn't revert the previous block, but will affect block reward distribution.

**Comment by asaj** [comment]
Yup. It used to be that if anything in epoch rewards distribution fails *no* epoch rewards will be distributed, essentially making all of epoch reward distribution atomic. This was changed in https://github.com/celo-org/celo-blockchain/pull/881, which allowed individual cUSD payments to validators to fail without reverting all of epoch reward distribution. In either case, failures in epoch reward distribution will not halt block production.
