### ISSUE TITLE
one tx have confused info in explorer

### ISSUE THREAD

**Issue by past2017** [celo-org/celo-blockchain#1099]
### Expected Behavior

in explorer, this tx 0x28f10652eb541e0f2edfa3ecd9fb1f292b4a9fedfecca7e62e9d63f620ec9659 should shown as normal

### Current Behavior

in explorer, this tx 0x28f10652eb541e0f2edfa3ecd9fb1f292b4a9fedfecca7e62e9d63f620ec9659 is shown as pending

### Steps to Reproduce Behavior

open https://explorer.celo.org/tx/0x28f10652eb541e0f2edfa3ecd9fb1f292b4a9fedfecca7e62e9d63f620ec9659/internal_transactions

### Logs

in wallet node, when get info with eth_getTransactionByHash, it looks this tx is included in blockNumber 0x11e075
```
 curl -s -X POST -H Content-Type:application/json -d '{"id": 0,"jsonrpc": "2.0","method": "eth_getTransactionByHash","params": ["0x28f10652eb541e0f2edfa3ecd9fb1f292b4a9fedfecca7e62e9d63f620ec9659"]}' http://127.0.0.1:12345
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "blockHash": "0x900240d219493bd1ac985abaddd4e52ccb3fa022498ceeb63dcd4978513d49cd",
    "blockNumber": "0x11e075",
    "from": "0xa200e072b147cf7f62136cdb023a1fb39b00b7c7",
    "gas": "0x5208",
    "gasPrice": "0x2540be400",
    "feeCurrency": null,
    "gatewayFeeRecipient": null,
    "gatewayFee": "0x0",
    "hash": "0x28f10652eb541e0f2edfa3ecd9fb1f292b4a9fedfecca7e62e9d63f620ec9659",
    "input": "0x",
    "nonce": "0x4",
    "to": "0x3066505c7d215161b4a8377818bad04f33bca6f7",
    "transactionIndex": "0x0",
    "value": "0x6046e78e724f4e000",
    "v": "0x149fc",
    "r": "0xd631b769258c583787a64034be7637c38f7286ee2c4d0c3dc144f0805fd40b5e",
    "s": "0x75c57224b8ef0b759233a909bc4338df7b9eda44538769866e461b62a1acc852"
  }
}

```

### System information

# geth version
Celo
Version: 1.0.0-stable
Git Commit: 8a44c2cd92200bdffce595c7558e84a39ea2bc15
Architecture: amd64
Protocol Versions: [65 64]
Go Version: go1.13.4
Operating System: linux

**Comment by mcortesi** [comment]
This seems to have been an issue with Blockscout (not geth). In the past we've experienced a few times where blockscout lags behind.

Thanks for reporting! Closing it here, since web team is already working on this kind of thing
