### ISSUE TITLE
Misleading log statement: Error sending all version certificates

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1100]
### Description

The following log is an example of a misleading log statement that appears quite often on validators, especially as they are syncing.

```
Jul 08 16:20:27 prod-celo-validator1a geth[1483]: INFO [07-08|16:20:27.663] Error sending all version certificates   func=RegisterPeer               err="shutting down"
Jul 08 16:20:27 prod-celo-validator1a geth[1483]: INFO [07-08|16:20:27.674] Error sending all version certificates   func=RegisterPeer               err="write tcp 178.162.153.74:30303->95.216.192.140:50708: use of closed network connection"
Jul 08 16:20:27 prod-celo-validator1a geth[1483]: INFO [07-08|16:20:27.766] Error sending all version certificates   func=RegisterPeer               err="shutting down"
Jul 08 16:20:28 prod-celo-validator1a geth[1483]: INFO [07-08|16:20:28.093] Error sending all version certificates   func=RegisterPeer               err="write tcp 178.162.153.74:30303->161.35.136.100:37056: use of closed network connection"
```

**Comment by udaya2899** [comment]
I'd like to contribute to this project. Would this be a good start? Any context would be appreciated

**Comment by nategraf** [comment]
@udaya2899 Potentially, but looking at this again, it looks like the logging level of this statement was reduced in 0609681b98b5316789cf744de724ce10b6e94dd6 and I would support that are the best way to handle this error. (It should still be reported when the request fails, but it only relevant if the operator is already looking into an issue.)

I am actually going to go ahead and close this issue. One that I think is much better to tackle as an introduction to contributing to Celo would be here https://github.com/celo-org/celo-blockchain/blob/master/consensus/istanbul/backend/announce.go#L625 (a one-line change) or here https://github.com/celo-org/celo-blockchain/issues/1066
