### ISSUE TITLE
Uptime Score Computation should work when using setHead()

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#1107]
The uptime score aggregator is stored within a leveldb and can have an incorrect value in some circumstances.  E.g. when the rpc api `setHead` is called, the value can become incorrect.

This ticket is to refactor how this aggregator is stored and calculated to be able to handle these scenarios.

**Comment by mcortesi** [comment]
This issues requires some research on what are all the potential causes for incorrect values, besides `setHead`

**Comment by gastonponti** [comment]
Fixed #1833
