### ISSUE TITLE
Revert #333 After upstream merge

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1131]
This upstream PR https://github.com/ethereum/go-ethereum/pull/20453 (which is actually a fix for a bug that @asaj submitted to upstream geth) should make this celo-blockchain PR unnecessary and revert-able:  https://github.com/celo-org/celo-blockchain/pull/333.

One thing to consider if the celo-blockchain PR is reverted is if it will still be backwards compatible.

_Originally posted by @kevjue in https://github.com/celo-org/celo-blockchain/pull/1115#issuecomment-665298849_

**Comment by oneeman** [comment]
Closing in favor of #1213
