### ISSUE TITLE
Light clients SBAT select peers based on location, other factors

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#115]
### Expected Behavior

Light clients should navigate to a full node that is close (by network latency).  
* Collect latency metrics at devp2p/gossip layer 
* ? gossiping of peers to include latency metrics ?
* preferentially make calls to close by full nodes

Maybe some of this already happens -- first step is to figure out current geth behavior!

**Comment by mcortesi** [comment]
superseeded by #1177
