### ISSUE TITLE
Devs SBAT be sure of Istanbul liveness 

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#116]
Istanbul has a liveness issue described in:
https://arxiv.org/pdf/1901.07160.pdf
https://drive.google.com/open?id=1v5kOvu5eppGHXdHqHoCIUMVmV7eAsDwpLljDtvVBR_U

and also described here:
https://github.com/ethereum/EIPs/issues/650#issuecomment-311836076

Istanbul learns of new blocks via miner/worker.go line 428, which results in a new FinalCommittedEvent being posted to the engine, handled at backend/handler.go line 123. Currently this just starts a new round.

**Comment by nambrot** [comment]
There was some additional conversation on https://github.com/jpmorganchase/quorum/issues/305
