### ISSUE TITLE
Full node stopped syncing 

### ISSUE THREAD

**Issue by Crypto2** [celo-org/celo-blockchain#1161]
Won't accept block 2592000 while running geth v1.0.1:

ERROR[09-20|17:32:54.164]
########## BAD BLOCK #########
Chain config: {ChainID: 42220 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0 Engine: istanbul}

Number: 2592000
Hash: 0xf6e714d2f1779bc9019b32eab17f32e635486e6abe38de64c13a74adadd3abef
         0: cumulative: 0 gas: 0 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x0000000000000000000000000000000000000000000000000000000000000000 logs: [0xc005c76790 0xc005c76840 0xc005c76c60 0xc005c76d10 0xc005c76dc0 0xc005c76e70 0xc005c76f20 0xc005c76fd0 0xc005c77080 0xc005c77130 0xc005c771e0 0xc005c77290 0xc005c774a0 0xc005c77550 0xc005c77600 0xc005c776b0 0xc005c77760 0xc005c77810 0xc005c778c0 0xc005c77970 0xc005c77a20 0xc005c77ad0 0xc005c77b80 0xc005c77c30 0xc005c77ce0 0xc005c77d90 0xc005c77e40 0xc005c77ef0 0xc00ad26000 0xc00ad260b0 0xc00ad26160 0xc00ad26210 0xc00ad262c0 0xc00ad26370 0xc00ad26420 0xc00ad264d0 0xc00ad26580 0xc00ad26630 0xc00ad266e0 0xc00ad26790 0xc00ad26840 0xc00ad268f0 0xc00ad269a0 0xc00ad26a50 0xc00ad26b00 0xc00ad26bb0 0xc00ad26c60 0xc00ad26d10 0xc00ad26dc0 0xc00ad26e70 0xc00ad26f20 0xc00ad26fd0 0xc00ad27080 0xc00ad27130 0xc00ad271e0 0xc00ad27290 0xc00ad27340 0xc00ad273f0 0xc00ad274a0 0xc00ad27550 0xc00ad27600 0xc00ad276b0 0xc00ad27760 0xc00ad27810 0xc00ad278c0 0xc00ad27970 0xc00ad27a20 0xc00ad27ad0 0xc00ad27b80 0xc00ad27c30 0xc00ad27ce0 0xc00ad27d90 0xc00ad27e40 0xc00ad27ef0 0xc00bc16000 0xc00bc160b0 0xc00bc16160 0xc00bc16210 0xc00bc162c0 0xc00bc16370 0xc00bc16420 0xc00bc164d0 0xc00bc16580 0xc00bc16630 0xc00bc166e0 0xc00bc16790 0xc00bc16840 0xc00bc168f0 0xc00bc169a0 0xc00bc16a50 0xc00bc16b00 0xc00bc16bb0 0xc00bc16c60 0xc00bc16d10 0xc00bc16dc0 0xc00bc16e70 0xc00bc16f20 0xc00bc16fd0 0xc00bc17080 0xc00bc17130 0xc00bc171e0 0xc00bc17290 0xc00bc17340 0xc00bc173f0 0xc00bc174a0 0xc00bc17550 0xc00bc17600 0xc00bc176b0 0xc00bc17760 0xc00bc17810 0xc00bc178c0 0xc00bc17970 0xc00bc17a20 0xc00bc17ad0 0xc00bc17b80 0xc00bc17c30 0xc00bc17ce0 0xc00bc17d90 0xc00bc17e40 0xc00bc17ef0 0xc00ca3a000 0xc00ca3a0b0 0xc00ca3a160 0xc00ca3a210 0xc00ca3a2c0 0xc00ca3a370 0xc00ca3a420 0xc00ca3a4d0 0xc00ca3a580 0xc00ca3a630 0xc00ca3a6e0 0xc00ca3a790 0xc00ca3a840 0xc00ca3a8f0 0xc00ca3a9a0 0xc00ca3aa50 0xc00ca3ab00 0xc00ca3abb0 0xc00ca3ac60 0xc00ca3ad10 0xc00ca3adc0 0xc00ca3ae70 0xc00ca3af20 0xc00ca3afd0 0xc00ca3b080 0xc00ca3b130 0xc00ca3b1e0 0xc00ca3b290 0xc00ca3b340 0xc00ca3b3f0 0xc00ca3b4a0 0xc00ca3b550 0xc00ca3b600 0xc00719d6b0 0xc00719c160 0xc00719c210 0xc00719c2c0 0xc00719c370 0xc00719c420 0xc00719c4d0 0xc00719c580 0xc00719c630 0xc00719c790 0xc00719c8f0 0xc00719ca50 0xc00719cc60 0xc00719cdc0 0xc00719cf20 0xc00719d080 0xc00719d1e0 0xc00719d290 0xc00719d340 0xc00719d3f0 0xc00719d4a0 0xc00719d550 0xc00719d600 0xc00719d760 0xc00719d810 0xc00719d8c0 0xc00719d970 0xc00719da20 0xc00719dad0 0xc00719db80 0xc00719dc30 0xc00719dce0 0xc00719dd90 0xc00719de40 0xc00719def0 0xc0039fc210 0xc0039fc370 0xc0039fc4d0 0xc0039fc790 0xc0039fc8f0 0xc0039fcb00 0xc0039fcc60 0xc0039fcf20 0xc0039fd080 0xc0039fd1e0 0xc0039fd340 0xc0039fd4a0 0xc0039fd6b0 0xc0039fd810 0xc0039fda20 0xc0039fdb80 0xc0039fdce0 0xc0039fde40 0xc00799c0b0 0xc00799c210 0xc00799c420 0xc00799c580 0xc00799c6e0 0xc00799c8f0 0xc00799ca50 0xc00799cdc0 0xc00799cfd0 0xc00799d130 0xc00799d290 0xc00799d3f0 0xc00799d550 0xc00799d6b0 0xc00799d8c0 0xc00799da20 0xc00799db80 0xc00799dce0 0xc00799de40 0xc00d0200b0 0xc00d020210 0xc00d020370 0xc00d0204d0 0xc00d020630 0xc00d020790 0xc00d0208f0 0xc00d0209a0 0xc00d020a50 0xc00d020b00 0xc00d020bb0 0xc00d020d10 0xc00d020e70 0xc00d020fd0 0xc00d021290 0xc00d0214a0 0xc00d0216b0 0xc00d021810 0xc00d021a20 0xc00d021ce0 0xc00d021ef0 0xc006218160 0xc006218370 0xc0062184d0 0xc0062188f0 0xc006218a50 0xc006218bb0 0xc006218d10 0xc006218f20 0xc006219130 0xc006219290 0xc0062193f0 0xc006219550 0xc006219760 0xc0062198c0 0xc006219a20 0xc006219b80 0xc006219ce0 0xc006219e40 0xc009a42160 0xc009a42420 0xc009a42630 0xc009a42790 0xc009a428f0 0xc009a42bb0 0xc009a42d10 0xc009a42e70 0xc009a42fd0 0xc009a43130 0xc009a43290 0xc009a433f0 0xc009a43600 0xc009a43760 0xc009a438c0 0xc009a43a20 0xc009a43b80 0xc009a43ce0 0xc009a43e40 0xc0079f60b0 0xc0079f6210 0xc0079f6370 0xc0079f6420 0xc0079f64d0 0xc0079f6580 0xc0079f6630 0xc0079f66e0 0xc0079f6790 0xc0079f6a50 0xc0079f6c60 0xc0079f6d10 0xc0079f6dc0 0xc0079f6f20 0xc0079f7080 0xc0079f7130 0xc0079f71e0 0xc0079f7290 0xc0079f7340 0xc0079f74a0 0xc0079f7600 0xc0079f7760 0xc0079f7970 0xc0079f7ad0 0xc0079f7c30 0xc0079f7d90 0xc0079f7ef0 0xc00c768000 0xc00c768160 0xc00c7682c0 0xc00c768420 0xc00c768630 0xc00c768790 0xc00c7688f0 0xc00c768a50 0xc00c768bb0 0xc00c768d10 0xc00c768e70 0xc00c769080 0xc00c7691e0 0xc00c769340 0xc00c7694a0 0xc00c7696b0 0xc00c769810 0xc00c769970 0xc00c769c30 0xc00c769d90 0xc00c769ef0 0xc00c8060b0 0xc00c806210 0xc00c806370 0xc00c806580 0xc00c8066e0 0xc00c806840 0xc00c806a50 0xc00c806bb0 0xc00c806d10 0xc00c807080 0xc00c8071e0 0xc00c807340 0xc00c8074a0 0xc00c8076b0 0xc00c807810 0xc00c807970 0xc00c807b80 0xc00c807d90 0xc00c840000 0xc00c840160 0xc00c8402c0 0xc00c840420 0xc00c840630 0xc00c840790 0xc00c8408f0 0xc00c840a50 0xc00c840bb0 0xc00c840d10 0xc00c840e70 0xc00c841080 0xc00c8411e0 0xc00c841340 0xc00c8414a0 0xc00c8416b0 0xc00c841810 0xc00c841970 0xc00c841ad0 0xc00c841ce0 0xc00c841e40 0xc00bfa0000 0xc00bfa00b0 0xc00bfa0160 0xc00bfa0210 0xc00bfa02c0 0xc00bfa0370 0xc00bfa0420 0xc00bfa04d0 0xc00bfa0580 0xc00bfa0630 0xc00bfa06e0 0xc00bfa0790 0xc00bfa0840 0xc00bfa08f0 0xc00bfa09a0 0xc00bfa0a50 0xc00bfa0b00 0xc00bfa0bb0 0xc00bfa0c60 0xc00bfa0d10 0xc00bfa0dc0 0xc00bfa0e70 0xc00bfa0f20 0xc00bfa0fd0 0xc00bfa1080 0xc00bfa1130 0xc00bfa11e0 0xc00bfa1290 0xc00bfa1340 0xc00bfa13f0 0xc00bfa14a0 0xc00bfa1550 0xc00bfa1600 0xc00bfa16b0 0xc00bfa1760 0xc00bfa1810 0xc00bfa18c0 0xc00bfa1970 0xc00bfa1a20 0xc00bfa1ad0 0xc00bfa1b80 0xc00bfa1c30 0xc00bfa1ce0 0xc00bfa1d90 0xc00bfa1e40 0xc00bfa1ef0 0xc00cfda000 0xc00cfda0b0 0xc00cfda160 0xc00cfda210 0xc00cfda2c0 0xc00cfda370 0xc00cfda420] bloom: 00020180280222120000a100600085294402004090563080c1002109091a2240890818838880c48000b164042f1884800031880330c03080005c8c00622211026690001025c2047e0041505a430e5da0081c185009e22d001012189042228c02040006300224900c2138040070040800064007809a011021681982928434970024802400830062424400107012e040021a45047180519802243680050006e831122330009121310d0301484b8c200c10188080005a2200040000518c445d9440802120022485ca420140e00e10a8c081080921050005380130a884106a0062809203018404480440080a2c292a21931010400001101b2800404430504d000835 state:

Error: invalid receipt root hash (remote: 7facee85f652204720b7f372545d378366f877e872481a8d808540a2304eba67 local: eac6ab375ddc99f70b3d5edd82ecb7f7cb4d7f2b8ca037c2fca9ca0eb4cef90a)
##############################

WARN [09-20|17:32:54.181] Synchronisation failed, dropping peer    peer=0db366021077da74 err="retrieved hash chain is invalid"

**Comment by Crypto2** [comment]
After resyncing from scratch it's now stuck again before 2626560:

ERROR[09-21|14:01:36.869]
########## BAD BLOCK #########
Chain config: {ChainID: 42220 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 0 Engine: istanbul}

Number: 2626560
Hash: 0x67ad0516de6f1ef13a3dfebe8319e11a73eaa319ce30bc9af368ed40b8c72544
         0: cumulative: 0 gas: 0 contract: 0x0000000000000000000000000000000000000000 status: 1 tx: 0x0000000000000000000000000000000000000000000000000000000000000000 logs: [0xc02727d970 0xc02727da20 0xc02727dad0 0xc02727db80 0xc02727dc30 0xc02727def0 0xc029ba8000 0xc029ba80b0 0xc029ba8210 0xc029ba8370 0xc029ba8420 0xc029ba84d0 0xc029ba8580 0xc029ba86e0 0xc029ba8790 0xc029ba8840 0xc029ba88f0 0xc029ba89a0 0xc029ba8a50 0xc029ba8b00 0xc029ba8bb0 0xc029ba8c60 0xc029ba8d10 0xc029ba8dc0 0xc029ba8e70 0xc029ba8f20 0xc029ba8fd0 0xc029ba9080 0xc029ba91e0 0xc029ba9a20 0xc035e120b0 0xc035e12160 0xc035e12210 0xc035e122c0 0xc035e12370 0xc035e12420 0xc035e12580 0xc035e12630 0xc035e126e0 0xc035e12790 0xc035e12840 0xc035e128f0 0xc035e129a0 0xc035e12a50 0xc035e12b00 0xc035e12c60 0xc035e12dc0 0xc035e12fd0 0xc035e13080 0xc035e13130 0xc035e131e0 0xc035e13290 0xc035e13340 0xc035e133f0 0xc035e134a0 0xc035e13550 0xc035e13600 0xc035e136b0 0xc035e13760 0xc035e13810 0xc035e138c0 0xc035e13a20 0xc035e13ad0 0xc035e13b80 0xc035e13c30 0xc035e13ce0 0xc035e13d90 0xc035e13e40 0xc035e13ef0 0xc028c7e000 0xc028c7e0b0 0xc028c7e210 0xc028c7e370 0xc028c7e790 0xc028c7e8f0 0xc028c7ec60 0xc028c7efd0 0xc028c7f290 0xc028c7f4a0 0xc028c7f8c0 0xc028c7fce0 0xc028c7fe40 0xc028c7fef0 0xc026df62c0 0xc026df64d0 0xc026df68f0 0xc026df6a50 0xc026df6b00 0xc026df6bb0 0xc026df6c60 0xc026df6d10 0xc026df6dc0 0xc026df6e70 0xc026df6f20 0xc026df6fd0 0xc026df7080 0xc026df7130 0xc026df7290 0xc026df73f0 0xc026df74a0 0xc026df7550 0xc026df7600 0xc026df7760 0xc026df7810 0xc026df78c0 0xc026df7970 0xc026df7a20 0xc026df7ad0 0xc026df7b80 0xc026df7c30 0xc0356dc0b0 0xc0356dc160 0xc0356dc210 0xc0356dc2c0 0xc0356dc370 0xc0356dc4d0 0xc0356dc580 0xc0356dc630 0xc0356dc6e0 0xc0356dc790 0xc0356dc840 0xc0356dc8f0 0xc0356dc9a0 0xc0356dca50 0xc0356dcb00 0xc0356dcbb0 0xc0356dcc60 0xc0356dcdc0 0xc0356dcf20 0xc0356dd1e0 0xc0356dd290 0xc0356dd340 0xc0356dd3f0 0xc0356dd4a0 0xc0356dd550 0xc0356dd600 0xc0356dd6b0 0xc0356dd760 0xc0356dd810 0xc0356dd8c0 0xc0356dd970 0xc0356dda20 0xc0356ddad0 0xc0356ddb80 0xc0356ddc30 0xc0356ddce0 0xc0356ddd90 0xc0356dde40 0xc0356ddef0 0xc02f630000 0xc02f6300b0 0xc02f630160 0xc02f630210 0xc02f6302c0 0xc02f630370 0xc02f630420 0xc02f6304d0 0xc02f630580 0xc02f630630 0xc02f6306e0 0xc02f630790 0xc02f630840 0xc02f6308f0 0xc02f6309a0 0xc02f630a50 0xc02f630b00 0xc02f630bb0 0xc02f630c60 0xc02f630d10 0xc02f630dc0 0xc02f630e70 0xc02f630f20 0xc02f630fd0 0xc02f631080 0xc02f631130 0xc02f6311e0 0xc02f631290 0xc02f631340 0xc02f6313f0 0xc02f6314a0 0xc02f631550 0xc02f631600 0xc02f6316b0 0xc02f631760 0xc02f631810 0xc02f6318c0 0xc02f631970 0xc02f631a20 0xc02f631ad0 0xc02f631b80 0xc02f631c30 0xc02f631ce0 0xc02f631d90 0xc02f631e40 0xc02f631ef0 0xc031b0a000 0xc031b0a0b0 0xc031b0a160 0xc031b0a210 0xc031b0a2c0 0xc031b0a370 0xc031b0a420 0xc031b0a4d0 0xc031b0a580 0xc031b0a630 0xc031b0a6e0 0xc031b0a790 0xc031b0a840 0xc031b0a8f0 0xc031b0a9a0 0xc031b0aa50 0xc031b0ab00 0xc031b0abb0 0xc031b0ac60 0xc031b0ad10 0xc031b0adc0 0xc031b0ae70 0xc031b0af20 0xc031b0afd0 0xc031b0b080 0xc031b0b130 0xc031b0b1e0 0xc031b0b290 0xc031b0b340 0xc031b0b3f0 0xc031b0b4a0 0xc031b0b550 0xc031b0b600 0xc031b0b6b0 0xc031b0b760 0xc031b0b810 0xc031b0b8c0 0xc031b0b970 0xc031b0ba20 0xc031b0bad0 0xc031b0bb80 0xc031b0bc30 0xc031b0bce0 0xc031b0bd90 0xc031b0be40 0xc031b0bef0 0xc03325a000 0xc03325a0b0 0xc03325a160 0xc03325a210 0xc03325a2c0 0xc03325a370 0xc03325a420 0xc03325a4d0 0xc03325a580 0xc03325a630 0xc03325a6e0 0xc03325a790 0xc03325a840 0xc03325a8f0 0xc03325a9a0 0xc03325aa50 0xc03325ab00 0xc03325abb0 0xc03325ac60 0xc03325ad10 0xc03325adc0 0xc03325ae70 0xc03325af20 0xc03325afd0 0xc03325b080 0xc03325b130 0xc03325b1e0 0xc03325b290 0xc03325b340 0xc03325b3f0 0xc03325b4a0 0xc03325b550 0xc03325b600 0xc03325b6b0 0xc03325b760 0xc03325b810 0xc03325b8c0 0xc03325b970 0xc03325ba20 0xc03325bad0 0xc03325bb80 0xc03325bc30 0xc03325bce0 0xc03325bd90 0xc03325be40 0xc03325bef0 0xc03475a000 0xc03475a0b0 0xc03475a160 0xc03475a210 0xc03475a2c0 0xc03475a370 0xc03475a420 0xc03475a4d0 0xc03475a580 0xc03475a630 0xc03475a6e0 0xc03475a790 0xc03475a840 0xc03475a8f0 0xc03475a9a0 0xc03475aa50 0xc03475ab00 0xc03475abb0 0xc03475ac60 0xc03475ad10 0xc03475adc0 0xc03475ae70 0xc03475af20 0xc03475afd0 0xc03475b080 0xc03475b130 0xc03475b1e0 0xc03475b290 0xc03475b340 0xc03475b3f0 0xc03475b4a0 0xc03475b550 0xc03475b600 0xc03475b6b0 0xc03475b760 0xc03475b810 0xc03475b8c0 0xc03475b970 0xc03475ba20 0xc03475bad0 0xc03475bb80 0xc03475bc30 0xc03475bce0 0xc03475bd90 0xc03475be40 0xc03475bef0 0xc035270000 0xc0352700b0 0xc035270160 0xc035270210 0xc0352702c0 0xc035270370 0xc035270420 0xc0352704d0 0xc035270580 0xc035270630 0xc0352706e0 0xc035270790 0xc035270840 0xc0352708f0 0xc0352709a0 0xc035270a50 0xc035270b00 0xc035270bb0 0xc035270c60 0xc035270d10 0xc035270dc0 0xc0306dc160 0xc0306dc2c0 0xc0306dc420 0xc0306dc580 0xc0306dc790 0xc0306dc9a0 0xc0306dcb00 0xc0306dcc60 0xc0306dcdc0 0xc0306dcf20 0xc0306dd080 0xc0306dd3f0 0xc0306dd550 0xc0306dd6b0 0xc0306dd810 0xc0306dda20 0xc0306ddb80 0xc0306ddef0 0xc028c7e160 0xc028c7e2c0 0xc028c7e420 0xc028c7e4d0 0xc028c7e580 0xc028c7e630 0xc028c7e6e0 0xc028c7e840 0xc028c7e9a0 0xc028c7ea50 0xc028c7eb00 0xc028c7ebb0 0xc028c7ed10 0xc028c7edc0 0xc028c7ee70 0xc028c7ef20 0xc028c7f080 0xc028c7f130 0xc028c7f1e0 0xc028c7f340 0xc028c7f3f0 0xc028c7f600 0xc028c7f760 0xc028c7f810 0xc028c7f970 0xc028c7fa20 0xc028c7fad0 0xc028c7fb80 0xc028c7fc30 0xc035040000 0xc0350402c0 0xc035040370 0xc0350404d0 0xc035040630 0xc035040840 0xc035040b00 0xc035040c60 0xc035040dc0 0xc035041080 0xc0350413f0 0xc035041550 0xc0350416b0 0xc0350418c0 0xc035041a20 0xc035041b80 0xc035041d90 0xc01e3f00b0 0xc01e3f0210 0xc01e3f04d0 0xc01e3f06e0 0xc01e3f0840] bloom: 00020180280222120000a100600085294402004090563080c1002109091a2240890818838880c48000b164042f1884800031880330c03080005c8c00622211026690001025c2047e0041505a430e5da0081c185009e22d001012189042228c02040006300224900c2138040070040800064007809a011021681982928434970024802400830062424400107012e040021a45047180519802243680050006e831122330009121310d0301484b8c200c10188080005a2200040000518c445d9440802120022485ca420140e00e10a8c081080921050005380130a884106a0062809203018404480440080a2c292a21931010400001101b2800404430504d000835 state:


Error: invalid receipt root hash (remote: ad5cd725666c0a7a41f37819ad48b2578167a5ff42cbfbef7e41a6d2a653348e local: 7a3032677de06a88f0f925d793c35959d8650e96dbcde204720c45a940859580)
##############################

WARN [09-21|14:01:36.869] Synchronisation failed, dropping peer    peer=8e72a3664df4fe37 err="retrieved hash chain is invalid"

**Comment by Crypto2** [comment]
These are the parameters I'm using: geth --nousb --networkid 42220 --ipcdisable --rpc --rpcapi "eth,net,web3,personal,admin,debug" --cache 4096 --syncmode fast --gcmode archive --bootnodes enode://5c9a3afb564b48cc2fa2e06b76d0c5d8f6910e1930ea7d0930213a0cbc20450434cd442f6483688eff436ad14dc29cb90c9592cc5c1d27ca62f28d4d8475d932@34.82.79.155:30301

**Comment by cmcewen** [comment]
Hi @Crypto2 - sorry to hear you're running into this. We've run into occasional issues with fast sync, so for now it may be best just to delete your datadir and resync using `full`

**Comment by Crypto2** [comment]
I've got it doing a full sync now. It is weird though because it ran for 12+ hours after fast sync ended both times.

**Comment by cmcewen** [comment]
That is definitely weird. Someone is looking into it, but hopefully this will get you unblocked for now. We also monitor Discord pretty heavily so if you want more real-time help, feel free to post there: http://chat.celo.org/

**Comment by nategraf** [comment]
@Crypto2 We managed to track down and fix this issue. `fast` sync is currently working on `master`, and we are in the process of making a new Celo blockchain client version available. Sorry for the trouble this caused you. https://github.com/celo-org/celo-blockchain/issues/1059
