### ISSUE TITLE
Devs SBAT be sure of Istanbul correctness

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#117]
Page 20 of https://arxiv.org/pdf/1901.07160.pdf describe a set of conditions under which correctness can be compromised in the Istanbul implementation.   Fix these! :-)

I believe (but haven't checked) that the Pantheon Istanbul implementation fixes this -- see here for more info: https://github.com/PegaSysEng/pantheon/tree/master/consensus/ibft

**Comment by kevjue** [comment]
> ### Section 5.2.1
> The scenario is basically
> ![image](https://user-images.githubusercontent.com/571810/53671035-9e651700-3c31-11e9-817c-a08e8b4a2238.png)
> 
> The proposer is byzantine, and with a segregated honest node set, it can achieve consensus with a single byzantine node under certain network assumptions.
> 
> The proposal by the paper is to:
> 
> 1. Change the quorom threshold from
>    ![image](https://user-images.githubusercontent.com/571810/53671307-a2456900-3c32-11e9-920c-6428c746609d.png)
> 
> to
> 
> ![image](https://user-images.githubusercontent.com/571810/53671352-d6b92500-3c32-11e9-86be-e18642d99aed.png)
> 
> So that for `n = 5`, you actually need 4 instead of 3 node consensus.

The paper's proposal for the new quorum size is actually wrong.  Specifically, it was assuming that two quorums only need to intersect at least 1 node, but it should intersect on at least f + 1 nodes.

@trianglesphere worked out the math so that the minimum quorum size should instead be "2f+ceiling((x + 1)/2)" where x = n - 3f.

**Comment by kevjue** [comment]
> Working on the first one. From first look, it looks like we do indeed listen at https://github.com/celo-org/geth/blob/nambrot/upstream-istanbul-merge/miner/worker.go#L357 for new finalized blocks and would thus move on to the next round. So the next task would be to create a more holistic end-to-end test and confirm that a
> 
> * node currently waiting for enough confirms
> * receives a finalized block
> * will move onto the next round appropriately
> 
> It's really mostly a miner/worker responsibility, but i guess we'll want to assert the state of the istanbul engine and duplicating what the miner/worker would do

I confirmed that this is true.

**Comment by kevjue** [comment]
> To answer the question around 5.1.2 I'm actually having trouble finding where the `CommittedSeal`s are checked at all. So far as I can tell, commit messages flow through `HandleMsg()` in `backend/handler.go`, to `handleEvents()`->`handleMsg()`(where it's checked to be from a member of the validator set)->`handleCheckedMsg()` in `core/handler.go`, to `handleCommit()` in `core/commit.go`, where the commit is accepted if it matches the current subject (tuple of `View, Digest`). Once the number of accepted commits is above the threshold, the seals are passed from `commit()` in `core/core.go` to `Commit()` in `backend/backend.go`, where the seals are added to a block which is then broadcast to the rest of the network and **I think** the node itself.
> 
> The seals are only checked in the engine's `VerifyHeaders` function, which **I think** is called upon receiving new blocks, which would only happen after the node receives its own broadcast.

The liveness fix (https://github.com/celo-org/celo-blockchain/pull/366) will address this issue, since the fix will do away with locks.  So this issue will become irrelevant.
