### ISSUE TITLE
LES protocol should support an optimized method for executing view calls

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1175]
## Context

One of the most common operations performed by light clients to to run a view call of a given smart contract. Examples include [querying the address associated with a set of identifiers from the Attestations contract](https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/identity/Attestations.sol#L613-L638) or estimating the gas required to execute a transfer.

As it stands the process for executing the function, and obtaining the result, is to:
1. Request the smart contract code and Merkle proof for an address with a `GetCodeMsg`
2. Run the code until a state variable is encountered.
3. Request the state variable and Merkle proof with a `GetProofsV2Msg`.
4. Run the code again. If an unknown state variable is hit go back to step 3.
5. Return the result.

Gas estimation in particular consists of running the same function call a number of time logarithmic in the block gas limit. (Note: I am not familiar with what caching exists for state variables, so I'm not sure how the total costs of multiple executions is to the costs of a single execution)

Because this protocol is requires a number of round trips for each request, at least 2 for any non-trivial request and often many more in practice, especially if the view call uses other contracts or libraries, this process is highly sensitive to network latency.

In practice, gas estimation for a simple cUSD transfer can require ~12 network round trips. If the client has a network latency of 200 ms, which can be commonly observed on mobile networks, this puts a lower bound of 6 seconds for gas estimation before considering an additional requirements of running the EVM, proof verification, and process scheduling.

## Proposal

In order to provide trustless view calls with one network round trip, the LES protocol could support a new message that will have the server execute a smart contract function. During execution, the server should record each state variable access key. Upon completion, the server would compile batched Merkle proofs for all contract code and state variable accessed during execution and send it back to the client. The client will then, without any further network calls, execute the smart contract function locally and obtain the result.

**Comment by mcortesi** [comment]
Before moving forward with this i would analyze the tradeoff and implication of adding such a call to the LES protocol.

LES Server has a flow control mechanism, where each call has cost. We need to understand which would be the cost of this function. And wether we would saturate full nodes by using it. 

Does it create a DoS opportunity for full nodes?

Additionally, batching merkle proofs begs the question of creating "aggregated proofs" that would be more space efficient for this use case

**Comment by oneeman** [comment]
Just a note in passing, which may not turn out to be relevant, but just in case, I wanted to point out that in PR #994 we increased the timeout for `eth_call` from 5 seconds to 50 seconds.  I'm not sure if this was in response to timeouts on light clients or what, but if we were to have LES servers do things similar to what call and estimateGas are doing, it might be of interest.
