### ISSUE TITLE
Implement CIP8 primitives for mobile access

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1176]
We need a total of 3 RPCs
    - decrypt, it was already added to the RPC, but my understanding that it has not yet been added to the native interface
    - `signTypedData`
    - `computeECDHSecret` being here [https://github.com/celo-org/celo-monorepo/blob/13dccc8f5ad20b9fa9b75e7b2b7dd80aaa9e6470/packages/contractkit/src/wallets/signers/local-signer.ts#L57](https://github.com/celo-org/celo-monorepo/blob/13dccc8f5ad20b9fa9b75e7b2b7dd80aaa9e6470/packages/contractkit/src/wallets/signers/local-signer.ts#L57)

Talk to @AlexBHarley for context/help

**Comment by hbandura** [comment]
Doing it in different PRs:
ecdh secret: #1219 
typeddata: #1220
