### ISSUE TITLE
Night Test: Full validator set change test to stress test announce protocol and multiproxy. 

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1186]
Create a Night Test that:

  1. Runs a testnet with a validator set size of 60.
  2. Performs a big validator set change (100%)
  3. Asserts the network behaves normally

**Comment by YoduYodu** [comment]
This linked PR to this issue is in a different repo: https://github.com/celo-org/infrastructure/pull/9/files

**Comment by trianglesphere** [comment]
PR Merged Dec 19 in celo-org infrastructure
