### ISSUE TITLE
(Re)Design Full Nodes Incentives

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1210]
This issue attempts to capture all ideas around Full node incentives. This refer to the incentive mechanism for fullnodes to provide a service to light clients.

Nowadays, that mechanism relays on `gatewayFee` and `gatewayFeeRecipient`; having full nodes expose their etherbase as their gateway address.

Here we (replace & ) capture prior ideas, that are currently under revision:

* #209 Full Node should only serve those client that "pay a fee" dropping those that don't do so
* #215 If full nodes expose their etherbase to lightclients, protocol needs to change to provide such address and when the address changes
* #359 If we have a market of fullnodes charging different fees, then light clients should select full nodes based on cost.
* #392 When we sign a tx for a single gateway, only that gateway will accept, hence it's a weakness
* #659 If we use gateway, full node should prioritize light client that pay better fees to them
* #1036 Full Nodes should be able to specify their gateway fee

**Comment by abhishekr700** [comment]
@mcortesi It appears all the PRs mentioned have been closed (completed?), so does the team have any approximate timeline when they're going to make the gateway fees live ?

**Comment by abhishekr700** [comment]
@mcortesi Thank you for the reply, I'm keen in running a full node post gateway incentives goes live !

**Comment by PeterEngler** [comment]
Any updates on the progress of this ?
I am running a full node for a couple of months now and it would be nice to get rewarded a little bit...
