### ISSUE TITLE
Reduce Binary Size for mobile clients

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1232]
**Is your feature request related to a problem? Please describe.**

When using celo-blockchain within a mobile application the geth binary ends up representing a huge part of the binary size. 

**Describe the solution you'd like**

Given that binary size is an importan quality on mobile environments, it would be important to reduce its size. 

There are several parts of the client that are of no use for mobile clients, so an idea here would be to remove the unused parts, and make it lighter. 

Additionally, we can review mobile build instructions and optimize them

**Comment by mcortesi** [comment]
Look into dead code paths or https://golang.org/pkg/go/build/#hdr-Build_Constraints

**Comment by hbandura** [comment]
Summary of research findings: https://www.notion.so/clabsco/2891c951f0324152ae5d8939f994bba1?v=030f84865d88430e9c43731627fff29b&p=e7de5b8131e84f3bb21a4c3512cbd0fb
