### ISSUE TITLE
Multi-Proxy should report information from all their proxies

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1234]
Currently, when in a multi proxy setup, stats reported to celo stats come from the proxy that's connected to celostats. This is incorrect.

We want to publish information from all the proxies and from the validators. As part of this issue we have to review the stats that we want to publish and display on celostats.

An interesting addition would be to report client version for the proxies and validator. Since this is the only existing way to obtain that information

**Comment by gastonponti** [comment]
superseded by #1252
