### ISSUE TITLE
Improve "missed in a row" log statement

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1247]
There is a metric that exposes the number of blocks missed in a row. (`blocksElectedButNotSignedGauge`)
When a block is missed the celo-blockchain client also logs.

Two changes should be made
1. Change "`missed in a row`" to `"missed_in_a_row"`
2. Enable to log to work without metrics being enabled (if metrics are disabled, `missed in a row` is always 0.

https://github.com/celo-org/celo-blockchain/blob/d5c014068f0053ff11f9a1f1feffcf878656a9cc/consensus/istanbul/backend/handler.go#L298

**Comment by nategraf** [comment]
* `missed in a row` is not out of what we consider to be the conventions for log labels. (i.e. Plenty of other log statements are space delimited) and changing this now might break some logging setups. I would recommend leaving it as is.
* After looking at the code and into metrics collection, I feel like there isn't really a great way enable tracking of that without it being a bit of a hack. Enabling and disabling metrics is a cost driven decision and forcing this metric to be on at all times violates the semantics of disabling metrics. I imagine that most validators setting up monitoring will have metrics on anyway. However, `Gauge` metrics are quite cheap, simply an int, so I could see a rational for making them default on. That would be a bigger change though.

**Comment by nategraf** [comment]
I've made some comment changes in this PR https://github.com/celo-org/celo-blockchain/pull/1272 and my recommendation is to close this issue, or reframe it around enabling `Gauge` metrics by default.

**Comment by trianglesphere** [comment]
Fixed by hiding the missed in a row message if we can't provide a valid number for it.
The other worse hack is to have a local var keep track of how many are missed or have some hack with enabling certain metrics.
