### ISSUE TITLE
Review geth configuration options (CLI flags and TOML handling)

### ISSUE THREAD

**Issue by oneeman** [celo-org/celo-blockchain#1264]
Review CLI flags and fix problems as needed.  A couple of known issues are already being addressed as part of #1263.

Things to check:
1. General precedence rule should be: `cfg` object built using defaults and TOML config, then values can be overridden using CLI flags
2. Configuration using TOML should work
3. CLI docs (what you see when you do `geth --help`) should be accurate.  
4. Default values should be sensible
5. We need to decide whether we want to keep this docs file or not: https://github.com/celo-org/celo-blockchain/blob/master/docs/docs/_interface/Command-Line-Options.md (added in #1075) .  If we want to keep it, we need a mechanism to keep it up to date.  Otherwise, we should remove it.

@trianglesphere I wasn't sure how to phrase what you mentioned relating to hotswap-related parameters.  Please edit this or comment on it with details.

**Comment by trianglesphere** [comment]
For hot swap, we create a level db called `replicastate`. Configuration in there takes precedence over the command line. 
The values saved in there that are configurable by the command line is the `--replica` flag. There is a little more internal configuration that is saved that is not configurable.

There is a way to make this an in memory DB, but that configuration is not exposed (need to set the path to be an empty string)

One tricky thing that needs to be cleaned up is that the level db will be created for full nodes, not just validators or proxies. PR here https://github.com/celo-org/celo-blockchain/pull/1228 to fix that. When a full node, it defaults to being a validator, not a replica (maybe a more sensical decision).

The goal of this is to prevent a validator that was swapped out from double signing if it was restarted (b/c it is not configured as a replica from the CLI, but it was set as a replica from the management console, so it needs to remember that it is a replica across restarts. The same can be done with a replica made a validator except the downside is missed signatures.
