### ISSUE TITLE
Make Celo's total difficulty calculations DRYer

### ISSUE THREAD

**Issue by oneeman** [celo-org/celo-blockchain#1290]
Since Celo uses Proof of Stake rather than Proof of Work, the concept of difficulty from Ethereum is not really applicable.  But, being a fork of go-ethereum, there are references to difficulty in many places.  We define the difficulty of each block as 1, so that (because the first block is block 0), the following formula holds:

```
total_difficulty = block_number + 1
```

And this is used at https://github.com/celo-org/celo-blockchain/blob/278176e05ac8646c1c3642d02134fd7000a5be64/core/types/block.go#L327

However, in other contexts (especially where one has the header but not the block), other methods are used, involving infrastructure inherited from go-ethereum that isn't necessary, such as `freezerDifficultyTable`, `HeaderChain.tdCache` and possibly others, as well as some duplication of the `number + 1` logic, as for example here: https://github.com/celo-org/celo-blockchain/blob/278176e05ac8646c1c3642d02134fd7000a5be64/core/headerchain.go#L152-L165 

We should try to make this more [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) and simple.  We need not necessarily rip out all the infrastructure inherited from go-ethereum, but we should definitely simplify ad aim to have the fundamental `block_number + 1` logic in one place.

In response to the code above from `headerchain.go`, @kevjue suggested having a method on `Header` which the method on `Block` can then use.  Later on I noticed the `HeaderChain.getTd()` method, which it would also be nice to have use this logic.  So perhaps we should have a standalone function `getTd(blockNumber uint64) uint64` which could then be used both there as well.  Regardless, the idea is to improve this in a relatively modest PR.

**Comment by piersy** [comment]
Looking through the freezer code brought me here, definitely no need to have that extra table storing td
