### ISSUE TITLE
Create benchmarking tool to measure scalability progress

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1320]
In order to measure our progress in scalability we need to have good benchmarking tool and guide on how to use them so we can measure how much we gain/loose from any change.

Requirements:

  * Have a conceptual model of block processing flow (& times) written into Notion
  * Optional: Have a statistical model we can use to perform simulation changing parameters or loading real data
  * Tool to measure block processing time (full blocks, semi full, empty)
  * Tool to measure consensus time (we should be able to play with different validator set sizes, and other consensus parameters)
  * Tool to measure block processing time with different sizes of stateDB storage.

**Comment by trianglesphere** [comment]
- k8s
- local
- test suite
- mainnet / baklava

----
Big Q: What does tx load make it look like?
TX Load generator for other environments: 
  - Single node block processor (pre-configured state db - from mycelo & mc/magic branch)
  - Build off Javi's load test work
  - What is the expected variance of block processing time w/ "realistic" or "malicious" load
  - Contract calls (more complex) vs cUSD transfers
     - Oracles
     - DEK / Account Info
     - Voting / Governance
     - Arbitrage / Exchanges / DeFi (Moola & Impact)

-----
Goal: Single node validator testnet on single machine
- Pre-loaded state db
- Start with transfers, but make it easy to apply different types of contract calls
- Need good instrumentation
