### ISSUE TITLE
Forno health probe should not take down the endpoint due to block delays

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-blockchain#1346]
We observed that around the epoch block the Forno health probe disabled routing to all Forno instances simultaneously. This lead to outages in ODIS which relies upon Forno for querying blockchain state.

https://console.cloud.google.com/net-services/loadbalancing/advanced/backendServices/details/rc1-forno-backend-service-http?project=celo-testnet-production&authuser=1&duration=PT1H

See Feb 3, 2021 9:16 AM PST

It seems to be caused by the last block in the epoch taking a longer time to create than expected.

**Comment by jcortejoso** [comment]
Thanks for sharing @codyborn.
We have typically observed longer block times around epoch, so I would agree we could introduce a different allowed delay just for the epoch blocks. Wdyt?

**Comment by codyborn** [comment]
That sounds good to me @jcortejoso. If it's possible, it'd be helpful to have a global rule for the health probe to ensure that not all nodes are taken down simultaneously, even if it believes they are all faulty. There may be other such sub-rules that are problematic in the future and this global rule would mitigate against this.

**Comment by oneeman** [comment]
Discussed this with Javi, and he suggested having the check instead be whether the pod is, for example, more than 5 blocks behind its neighbor.  That way if a block takes a long time it won't have an impact on the health check since all the pods will be waiting and none will fall behind relative to the others.

Another possibility, but more complex, is to have an external service that aggregates the latest block number from all the nodes, and each node's health check could compare its latest block to that rather than to its neighbor.

**Comment by jcortejoso** [comment]
I have been testing the approach described by @oneeman. This approach requires that each pod should be able to connect his "pair" at port 8545 (to check the head from that block). There are different approaches to be able to connect among them:

-  Pods can reach each other using the pod ip. Pod ips are not known by the pods (they only know their own ip), so this approach would need to use kubernetes api to request the pod information (which requires granting the permissions to the default service account of the namespace, or create a service account for the pods that can read the pod description from kubernetes api). Also this requires to have a kubernetes client in the geth container to run the healthcheck script.

- We could create an independent service for each pod at port 8545, as we have now for port 30303. This approach can have the downside to expose (at least cluster internally) the rpc ports to any process running in the cluster, which may be not be desired.

- Pods that are part of a statefulset are assigned a fqdn that can be resolved by any other pod in the cluster if you assign the field `StatefulSet.spec.serviceName` to an existing headless service that points to that statefulset. Right now we are configuring this field to a no headless service, so the DNS does not work. I have checked if using a headless service if it'd work and it does, but the clear downside is that the field `StatefulSet.spec.serviceName` is immutable so we'd need to delete and recreate the statefulsets. More info about this issue: https://github.com/kubernetes/kubernetes/issues/45779

I do not have a strong opinion about which option fits better. In my option the third option is the cleanest and more appropriate, but breaking the statefulset upgradibility seems a strong cons and the deployment would require some extra work. Between the other two options both have also clear downsides, so I not sure if we should proceed with any of those or maybe thinking on another approach, at least temporally,  for solving this issue.

In the long term and reading the issue about the statefulset serviceName, I think we should configure that service to the headless service as seems the expected way to do.

**Comment by nategraf** [comment]
One of the risks of using the pods neighbor as a reference is that it's possible for all of them to become unhealthy together, at which point we wouldn't detect a failure. One options would be to use the peer list, which includes information about the peers's block number, as a way to compare their sync status to all peers. Here is an example of how to query in the `geth` console for all nodes at least 6 blocks ahead
```javascript
admin.peers.filter(function(p) { return !!p.protocols.istanbul }).map(function(p) { return p.protocols.istanbul.difficulty - eth.blockNumber }).filter(function(diff) { return diff >= 5 }).length
```

**Comment by oneeman** [comment]
I like this idea!  The only (and somewhat fanciful) concern is if we had malicious nodes pretending to have higher difficulty than they really do (which I imagine eventually leads to disconnecting them, but not immediately).  The risk of that causing problems could be reduced by combining with checking the age of the last block.  I'm not sure about the precise condition to use, but it could be something like

```
oldBlock := last block is >= 30 seconds old
behindPeers := have peers which are >= 5 blocks ahead of us
lackingPeers := have < 5 peers running istanbul
unhealthy := lackingPeers || (oldBlock && behindPeers)
```

Then we could also have a more relaxed alert on just the age of the last block (a few minutes), which would trigger if there is a prolonged network stall (longer than long epoch blocks).

I struggle to think of what could cause a node to be unhealthy with these criteria except networking problems or other reasons for being unable to have peers.  In other words, I can't think of reasons why a node would fall behind when it has peers which are up to date.  But I guess it couldn't hurt to check, and it would solve the problem we currently have of relying only on the time of the last block.
