### ISSUE TITLE
MyCelo: Complete migrations on

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1362]
The ones left are attestations, validators, governance

**Comment by oneeman** [comment]
Branch is https://github.com/celo-org/celo-blockchain/tree/oneeman/mycelo-missing-contracts .  @mcortesi will do the `25_elect_validators` migration

**Comment by oneeman** [comment]
@mcortesi I pushed the attestations and governance migrations.  For governance, I skipped setting the constitution thresholds and transferring core contract ownership, as in all the existing configs in celo-monorepo we are skipping those steps.  Adding the ownership transfer would be easy and quick if we want to later on.  Support for a constitution would be more tedious.  I'm going to reassign this issue to you as you're working on the ElectValidators migration.

**Comment by oneeman** [comment]
This has already been finished in https://github.com/celo-org/celo-blockchain/pull/1409
