### ISSUE TITLE
MyCelo: Figure out a way of enable/disabling features on migrations (can be disable migrations)

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1363]
## Description

Figure out a way of enable/disabling features on migrations (can be disable migrations)
Add an optional flag on each migrations config to see if it should be skipped.

## Context
This allows turning contract features like governance off it testnets.

**Comment by oneeman** [comment]
It's unclear how much of a use there is for this presently.  So I will remove it from the epic (#1355) so that we can close the epic out.
