### ISSUE TITLE
Investigate snapshot efficacy and merge 1.10 database changes into Celo blockchain

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#1427]
Geth 1.10 includes performance-relevant changes to the database (e.g. snapshots). Merge those changes into Celo blockchain.

* [ ] Gather existing performance data on snapshots
* [ ] Merge upstream DB changes into Celo
* [ ] Measure performance impact of changes

**Comment by mcortesi** [comment]
Replaced by other issues
