### ISSUE TITLE
Verify bls signatures in aggregate rather than individually

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-blockchain#1434]
Currently verifying bls signatures is a bottleneck for consensus - https://www.notion.so/clabsco/Aggregated-BLS-signature-verification-for-commit-messages-a837c2aac87040cbb08b9fc518c4f701

In order to be able to verify bls signatures in aggregate the structure of the code needs to be modified to support this, since at present bls signatures are verified individually, allowing us to gate their addition to the round state. If we move to verifying the signatures in aggregate we need a way to be able to identify which signatures are bad if the aggregate is bad and also a way to remove or mark the bad messages so that they do not break subsequent attempts to verify the signature in aggregate.

To be considered done we need to run a testnet and see that it continues to function in the face of validators sending messages with bad bls signatures.

**Comment by piersy** [comment]
Under review but lots more work required to resolve comments.

**Comment by piersy** [comment]
Under review, quite a lot of work is required to resolve all PR comments.

**Comment by piersy** [comment]
@kobigurk @gtank Just wondering what the status of the streaming bls work is?

**Comment by piersy** [comment]
Shelving this, while I pursue work on reliability #1656

**Comment by kobigurk** [comment]
@piersy FYI, the implementation is being reviewed now: github.com/celo-org/celo-bls-snark-rs/pull/222
