### ISSUE TITLE
## Expected Behavior

### ISSUE THREAD

**Issue by berti441** [celo-org/celo-blockchain#1524]
## Expected Behavior

_Please describe the behavior you are expecting_

## Current Behavior

What is the current behavior?

## Steps to Reproduce Behavior

_How can we reproduce this?_

## Logs

_Are there any logs?_

## System information

Run `geth version`

__Originally posted by @berti441 in https://github.com/celo-org/celo-blockchain/issues/1521__

**Comment by berti441** [comment]
Bonjour,

Je souhaite récupérer mon token celoclgd et le placer sur mon wallet coinbase .

Est ce que c est possible ?

Et si oui comment faire

**Comment by trianglesphere** [comment]
Hello,

It's possible to move CELO to your coinbase wallet, but that depends on where your token currently is.
If you scroll to the bottom of https://celo.org/community and click on "chat" that will take you to the discord which will be more helpful.

C'est possible.
D'où veux-tu récupérer ton token CELO?
