### ISSUE TITLE
Improve shutdown behaviour

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1548]
## Description

Shutdown behaviour is suboptimal. In particular we see that:
 * It takes too much to shutdown
 * Data corruptions can be on the last 100k blocks (users on discord have reported losing 300k blocks when power cycling a validator machine)

For this task, requirement is to understand why it takes to so long to shutdown and how can that be improved and of course, do it.

Similarly, why corruption can be of 100k blocks? when common sense indicates that only the most recent blocks should be "corruptible". And then improve this too.

If we realize this task is much more complex than anticipated, we can stop at research level, and create new issues for different subtasks.

## Context

Improving shutdown behaviour would be quite beneficial to our node operators. We seens too many times in the community how nodes are down for several hours after a data corruption issue due to a bad shutdown.

**Comment by oneeman** [comment]
Regarding how far back the node rewinds, this issue seems relevant: https://github.com/ethereum/go-ethereum/issues/20383 (hat tip to @jcortejoso for finding it).

**Comment by William-DERENNE** [comment]
Hi,
is the --cache.database if set to zero, ( --cache.database "0" ) forces writing direct to disk ?
