### ISSUE TITLE
make android gives me Error 1

### ISSUE THREAD

**Issue by chrishobcroft** [celo-org/celo-blockchain#1553]
## Expected Behaviour

I expect `make android` to make something to do with Android, which I'm keen to discover.

## Current Behaviour

When I run `make android`, it gives me this:

```
ubuntu@celo:~/celo-blockchain$ make android
Applying patch for mobile libs...
git apply patches/mobileLibsForBuild.patch
error: patch failed: go.mod:75
error: go.mod: patch does not apply
make: *** [Makefile:70: android] Error 1
```

## Steps to Reproduce Behaviour

```
sudo apt update
sudo apt install -y make gcc
wget https://golang.org/dl/go1.16.4.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.4.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin
git clone https://github.com/celo-org/celo-blockchain.git
cd celo-blockchain
make android
```

**Comment by trianglesphere** [comment]
Hi, could you report the output of `git status`? One thing to check is that running `make android` several times in a row will probably causes issues if `go.mod` is not restored between each run (as the patch can only be applied once).
