### ISSUE TITLE
Autoscaling Forno

### ISSUE THREAD

**Issue by jcortejoso** [celo-org/celo-blockchain#1572]
Implement forno autoscaling, with the consideration of having a low starting time for new nodes (for example having the volumes already created and with recent chain state).

**Comment by jcortejoso** [comment]
We have not started working on this yet. To scale up or down forno we need to scale using kubernetes or celotool manually.

**Comment by mcortesi** [comment]
since we use session affinity, this is not something we want to do fo now. Closing until it makes sense
