### ISSUE TITLE
Coinbase CELO Transfer to Ledger Wallet

### ISSUE THREAD

**Issue by jwmc141** [celo-org/celo-blockchain#1599]
I transferred my CELO tokens to my ETH wallet on my Ledger NanoX. I made the mistake and assumed that Ledger supported CELO since it was an ERC20 token. I used the ETH address provided by Ledger to transfer my CELO out of my Coinbase account. I verified the address, and Coinbase showed it was a good receiving address. So I thought the transfer was good. After the transfer and realizing that Ledger didn’t support CELO, I have searched Etherscan.io  to see if I could see the transaction, and there is no evidence that it exists. Please help. How do I find my CELO, and put it on my CELO wallet?

**Comment by trianglesphere** [comment]
Hi @jwmc141 this has a couple options on how to recover CELO from an eth address: https://docs.celo.org/celo-owner-guide/eth-recovery
Here is the guide on how to use a Ledger with CELO: https://docs.celo.org/celo-owner-guide/ledger

Lastly, you'll want to use explorer.celo.org to look for the transaction.
