### ISSUE TITLE
Update GPM parameters

### ISSUE THREAD

**Issue by oneeman** [celo-org/celo-blockchain#1666]
We are currently using a target density of 50%.  This means that in the steady-state mode (where the GPM is not rapidly increasing or decreasing), blocks would on average be half full.  To put it another way, we are currently supporting a "burst" of 100% relative to normal usage (since 100% full is 2x of 50% full), and increasing the GPM when this burst support is used.

If we increase the target density then the normal (non-burst) capacity would be higher while keeping the block gas limit the same.  0.75 or 0.8 has previously been suggested as reasonable values.  This would be done as a governance proposal.  However, we should first revisit the topic in order to come to more informed and deliberate proposed values for:

(a) the target density
(b) the adjustment speed

Specifically, we should consider the resulting GPM adjustments, including the effect of their not being symmetrical (e.g. if the target density is 0.8 then a single validator with an empty block can lower the GPM by as much as it would increase due to 4 full blocks, opening up the possibility of a minority of validators manipulating the GPM to be lower, see Roughgarden's paper and https://discord.com/channels/600834479145353243/783326878806048819/870393367937298472)

This github issue includes both the investigation and the creation and shepherding of a resulting governance proposal.

Some more background can be found at https://www.notion.so/clabsco/Increase-EIP1559-block-utilization-target-31aa37eadd5546ea94097dfb51c69b0b , as well as:
* Vitalik post on resource pricing: https://ethresear.ch/t/draft-position-paper-on-resource-pricing/2838
* Tim Roughgarden's analysis: https://timroughgarden.org/papers/eip1559.pdf

**Comment by mcortesi** [comment]
Done already
