### ISSUE TITLE
Archive nodes and blockscout timeout problems

### ISSUE THREAD

**Issue by jcortejoso** [celo-org/celo-blockchain#1680]

**Comment by jcortejoso** [comment]
From some time to now we have been observing an increasing number of timeouts in archive nodes with rpc requests coming from blockscout using the method `debug_traceTransaction`.
Blockscout pending transaction queue now is growing faster that blockscout is able to index so we need to find a solution to:
- Being able to keep on track with the new pending tx and reduce the queue.
- Debug why the request time outs.

**Comment by quang390221** [comment]
Sometimes I encountered this case
