### ISSUE TITLE
how to change 500 celo cap of celo load bot?

### ISSUE THREAD

**Issue by rachit77** [celo-org/celo-blockchain#1697]
## Description

How can  I change celo load bot hard cap of 500 celo in my local devnet. Celo load bot can only have 500 celo to pay for gas fees.

## Context
I am implementing local devnet of celo's blockchain .
To introduce state bloat in the devnet , I need more celo to pay for gas fees.

**Comment by YoduYodu** [comment]
https://github.com/celo-org/celo-blockchain/blob/master/cmd/mycelo/README.md
Not very familiar with this, but could you try customize the config here? e.g. increase the balance in genesis, or modify the hard cap(not sure if it's available though)

**Comment by trianglesphere** [comment]
Accounts are funded here: https://github.com/celo-org/celo-blockchain/blob/46dac5739da3f29a14339c188a0d9774c2d28e8c/mycelo/genesis/genesis.go#L52
I'd also look through `cmd/mycelo/templates.go` to make sure you're using the `loadtest` one.

Having the commands that you're running is also extremely helpful.

**Comment by rachit77** [comment]
> Accounts are funded here:
> 
> https://github.com/celo-org/celo-blockchain/blob/46dac5739da3f29a14339c188a0d9774c2d28e8c/mycelo/genesis/genesis.go#L52
> 
> 
> I'd also look through `cmd/mycelo/templates.go` to make sure you're using the `loadtest` one.
> Having the commands that you're running is also extremely helpful.

ok
