### ISSUE TITLE
Merge upstream up to 1.10.7

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-blockchain#1699]
## Description

Bring upstream changes up to 1.10.7. Adapt those changes to celo and include them in the next hardfork (E Hardork)

To Do

- [x] Lint
- [x] Build iOS
- [x] Build Android
- [x] TestEthClient
- [x] TestForkIDSplit
- [x] GraphQL Tests
- [x] TestStateProcessorErrors
- [x] EthSuite Test (Needs RLP conversion)
- [x] TestChain_GetHeaders (in `cmd/devp2p`)
- [x] Disable snap sync
- [x] Handle flags
- [x] Merge master
- [x] Block Receipts Issue
- [x] 1559 Gas price suggestion
- [x] Remove `OpBaseFee`

## Context

 * Important to be synced with upstream
 * Required changes to include berlin and london HF into celo

**Comment by trianglesphere** [comment]
# Flag Changes from 1.4 to 1.5 (For release notes)


The following previously deprecated flags have been removed.
```
--pprofport value                  use --pprof.port
--pprofaddr value                  use --pprof.addr
--memprofilerate value             use --pprof.memprofilerate
--blockprofilerate value           use --pprof.blockprofilerate
--cpuprofile value                 use --pprof.cpuprofile
--bootnodesv4                      use --bootnodes
--bootnodesv5                      use --bootnodes
```


The following flags have been removed
```
--vm.evm                           no substitute
--vm.ewasm                         no substitute
WHISPER (EXPERIMENTAL) OPTIONS
--shh                              no substitute
--shh.maxmessagesize value         no substitute
--shh.pow value                    no substitute
--shh.restrict-light               no substitute
```

The following flags have been added
```
--datadir.minfreedisk
--usb
--mainnet
--txlookuplimit
--light.nosyncserve
--cache.preimages
--http.rpcprefix
--ws.rpcprefix
--bloomfilter.size
```

The following flags have been deprecated and will be removed in a future release.
```
--nousb                            USB defaults to off. Use --usb to enable
--backtrace                        use --log.backtrace
--debug                            use --log.debug
--consoleformat                    use --log.json (true for JSON, false for Term output format)
```
