### ISSUE TITLE
Espresso Hardfork

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1703]
## Description

This issue is tracking what needs to be done for the Espresso Hardfork.

Code Changes
- [x] https://github.com/celo-org/celo-blockchain/pull/1695
- [x] https://github.com/celo-org/celo-blockchain/pull/1696
- [x] Geth v1.10.8 (at least the hotfix appropriately HF gated)
- [x] https://github.com/celo-org/celo-blockchain/pull/1712
- [x] https://github.com/celo-org/celo-blockchain/pull/1676
- [x] Add CELO typed tx

Once the client is code complete, then begins the testing phase.

- [x] Sync test
- [x] Ephemeral testnet (testing HF activation & all EIPs & CIPs)
- [x] Rollout to Baklava
- [ ] Rollout to Alfajores
- [ ] Rollout to Mainnet

When the ephemeral testnet tests are passing, we'll release a new version of the celo blockchain client with an activation block number for baklava. After tests pass on Baklava & Alfajores, we'll release another version with the activation block for mainnet.

**Comment by piersy** [comment]
This has clearly been done!
