### ISSUE TITLE
The bind_v2 module does not use EIP155 signing

### ISSUE THREAD

**Issue by erwanor** [celo-org/celo-blockchain#1709]
## Problem

Replay-protected transactions are mandatory on Celo. But, the `bind_v2` module does not use custom signers (`types.EIP155Signer`) which makes transactions fails since they do not incorporate a hashed `chainId`.

See: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md for more information

## Expected Behavior

Using `bind_v2` transactors (`TransactOpts`) should result in consensus-compliant transactions. 

## Current Behavior

Using the `bind_v2` auth methods to sign a contract interaction with side-effects result in the following error when I attempt to broadcast it:

`2021/10/04 11:22:03 replay protection is required`

## Steps to Reproduce Behavior

I have put together a [repo](https://github.com/aaronwinter/celo-blockchain) where you can play with a simple example (`Counter` contract) that already has bindings generated for it. The repository refers to a fork of the `v1.4.0` of `celo-blockchain` that implements a quick fix (use `EIP155Signer`) as well as the legacy faulty methods:

1. geth account new
2. Fund account with Alfajores Celo
3. `git clone git@github.com:aaronwinter/replay-celo-bug`
4. Paste path to keystore file (step 1) into `PATH_TO_SK` 
5. `go build`

## Suggested solution

A quick fix is implemented here: https://github.com/celo-org/celo-blockchain/commit/b43ccca34c6e2a85528b8d0f8866b97c0caff54c#diff-b131b5817056f73e717d9d01f3d3094d0da99dd792e7d537402c3522fac167b4R101

Some of the changes made to the bind module (`bind_v2`) are quite nice, but it should meet the upstream `geth` interface (see: https://github.com/ethereum/go-ethereum/commit/ed0670cb17a96aafeb9eaaeb9765a42fb6bb5663#diff-18aeac66ddb948fefafc8c96289984cd90c94c54d0616e96165ffff8865b6250R130).

## System information

Using Celo geth `v1.4.0` (fork is at `v1.4.2`)

**Comment by mcortesi** [comment]
Hi @aaronwinter; great to see you've taken a look at `bind_v2`. It was a sort of quick solution to simplify bind, and add some features to it. But it was done while doing other things, so i can't say i gave it enough thinking to it.

Are you using it? Do you have any ideas for it? Would you be willing to contribute to it? That would be great.

Also,  happy to review any PR you send fixing this.

**Comment by erwanor** [comment]
Hey @mcortesi ! apologies for the late reply, I got pulled away by other items. Yes, I would be happy to turn this fix into a proper PR. The most cost-effective way to get this fixed is simply to adopt geth's transactor API (`NewTransactorWithChainId`) and make it compatible with Celo (on `bind_v2`).

I don't know what to make of the old `bind` module though. I understand that it's kept in the codebase for backward compatibility, bu is there a plan to phase it out and transition the rest of the codebase to `bind_v2`. This is definitely another PR but I would like to hear your thoughts on this.

**Comment by erwanor** [comment]
Fixed in #1695 I believe
