### ISSUE TITLE
Investigate Pending txs increase in 1.4

### ISSUE THREAD

**Issue by hbandura** [celo-org/celo-blockchain#1725]
There has been an increase in the pending txs amount since the 1.4 update. It seems to be steadily rising so it merits at least a time-boxed investigation.

As @jcortejoso wrote:
```
I think Mariano and me observed today is that the number of pending transactions in v1.4.0 
has increased notably, compared to previous releases: (first image is for v1.4.0 nodes, 
and second for v1.3.2 nodes).

Can anyone think on any reason or change that could have caused this?
```

![image.png](https://images.zenhubusercontent.com/5f8f1a3d86fbfd3a682082dc/b2a7082e-5812-4c71-8340-e0d48883830b)

![image.png](https://images.zenhubusercontent.com/5f8f1a3d86fbfd3a682082dc/39dadb00-477b-49b3-b642-bda17a31718b)

![image.png](https://images.zenhubusercontent.com/5f8f1a3d86fbfd3a682082dc/ac9eb1cb-b636-433c-9319-64e5f011bbbb)

@gastonponti added:
```
mmmm, maybe this PR: https://github.com/ethereum/go-ethereum/pull/21300

That was merged in the 1.9.18 version (between the 1.3.2 and 1.4.0, 
we added the 1.9.16-1.9.19 versions from upstream)
```
link: https://github.com/ethereum/go-ethereum/pull/21300

**Comment by mcortesi** [comment]
Discovered it was related to the miniming gas price requirement. Tx with gas price cero were being accepted

https://github.com/celo-org/celo-blockchain/pull/1749
