### ISSUE TITLE
Run geth fuzzing tests

### ISSUE THREAD

**Issue by trianglesphere** [celo-org/celo-blockchain#1752]
## Description

There are a lot of tests that geth has that we do not run specific to the evm or other state protocols

## Context

There are tests that are written outside go to test specific components. Being able to run them would be helpful.

**Comment by piersy** [comment]
@trianglesphere, are you referring to the retesteth tests?

**Comment by trianglesphere** [comment]
no. Geth added a bunch of stuff in the `tests` folder that could be run.
