### ISSUE TITLE
udp listen port is not always unbound when using lightest client.

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-blockchain#1867]
## Description

Repeatedly running `./geth --datadir lightest --syncmode lightest --port 30303` and then closing using `ctrl-c` sometimes results in the oprating system thinking that udp port 30303 is still bound even after the server has shut down. This prevents re-running geth with the same port `Fatal: Error starting protocol stack: listen udp [::]:30303: bind: address already in use`. This state remains despite waiting several hours, the workaround is to change the port.

System: `uname -a
Darwin C02FV1SBMD6R 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin`

**Comment by kehiy** [comment]
@carterqw2 you can check #2147
