### ISSUE TITLE
deployExchanges() doesn't work to generate Genesis

### ISSUE THREAD

**Issue by hiromaily** [celo-org/celo-blockchain#1884]
## Description
I tried to run localnet following to [Mycelo](https://github.com/celo-org/celo-blockchain/blob/master/cmd/mycelo/README.md).
But `execution reverted` happened after `mycelo genesis` command run.

There are some deploy functions in [deploy()](https://github.com/celo-org/celo-blockchain/blob/master/mycelo/genesis/genesis_state.go#L79), but only [ctx.deployExchanges](https://github.com/celo-org/celo-blockchain/blob/master/mycelo/genesis/genesis_state.go#L497) doesn't work.

## Current Behavior
`execution reverted` happened

## Context
after `mycelo genesis` command run

part [Mycelo](https://github.com/celo-org/celo-blockchain/blob/master/cmd/mycelo/README.md)

## Proposed Solution
after commenting out [ctx.deployExchanges](https://github.com/celo-org/celo-blockchain/blob/master/mycelo/genesis/genesis_state.go#L497), command works.

**Comment by hiromaily** [comment]
This error would cause by this changes in celo-monorepo
https://github.com/celo-org/celo-monorepo/commit/1114edb5edc727f56453dab34a28a9f62667030b

`mycelo/genesis/base_config.go` needs to be compatible with this change.

**Comment by Activatorq1** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14156445/

**Comment by carterqw2** [comment]
Should be fixed here https://github.com/celo-org/celo-blockchain/pull/2010
