### ISSUE TITLE
Validators SBAT use hardware wallets for validator key

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#190]
### Expected Behavior

We got a Nano Ledger S and we should be able to use it for the validator key pair. Configure it and document what needs to be done to make that work.  (We need to add that to the 'how to run a validator' documentation when we write it). 

Check with @asaj about compatibility with long-term plans around ultra-light client sync and its ZK proof requirements. 

### Current Behavior

Geth supports hardware wallets but we haven't tested it.

**Comment by mcortesi** [comment]
superseeded by #225
