### ISSUE TITLE
TobinTransfer will charge tobin tax even when transferring to self

### ISSUE THREAD

**Issue by diwu1989** [celo-org/celo-blockchain#1935]
TobinTransfer signature
`func TobinTransfer(evm *vm.EVM, sender, recipient common.Address, amount *big.Int) {`
I think if sender == recipient, then the tax shouldn't be charged.

I know tobin is off right now and hasn't ever been turned on, so it's possible to fix this on mainnet without hardfork.

**Comment by palango** [comment]
@diwu1989 Thanks for reporting this.

> I know tobin is off right now and hasn't ever been turned on, so it's possible to fix this on mainnet without hardfork.

Sadly this is not true for the testnets.



However, the CIP to remove the tobin tax has been accepted and it will be removed in this PR: https://github.com/celo-org/celo-blockchain/pull/2029.
