### ISSUE TITLE
Update prepare-system-contracts Make rule to support working with commits and not branches

### ISSUE THREAD

**Issue by piersy** [celo-org/celo-blockchain#1956]
Currently `prepare-system-contracts` tries to enforce use of only commit hashes or tags for the `monorepo_commit` but in fact fails, since it is possible to clone a branch on the first invocation. Additionally `prepare-system-contracts` does not support the use of commit hashes on first invocation.

The problem with using branchnames in the `monorepo_commit` file is that the make rule is triggered to clone or update the repo only when `monorepo_commit` is changed, so putting a branch name into `monorepo_commit` would work on first invocation, but would not subsequently trigger rebuilding of contracts when the branch changes.

**Comment by gastonponti** [comment]
This should have a low priority. Even if it is a problem if someone wants for example to add `master` as the `monorepo_commit` there still easier workarounds as for example removing the repo, which will update the new checkout.

For the commit part, to be honest, as we are the ones maintaining the branches in the monorepo that we are setting here, if we don't reuse branches, and treat everything as tags, this shouldn't be a problem. The only case where someone should fix a commit would probably be on development mode, and that dev could checkout that particular branch and rebuild or as I said before, just remove the monorepo.

So, a nice-to-have from my point of view is we are not updating branches in the monorepo.

**Comment by karlb** [comment]
This can be achieved with
```diff
diff --git a/Makefile b/Makefile
index 04eef3f2f..c049a194d 100644
--- a/Makefile
+++ b/Makefile
@@ -89,7 +89,7 @@ $(MONOREPO_PATH): monorepo_commit
        @set -e; \
        mc=`cat monorepo_commit`; \
        echo "monorepo_commit is $${mc}"; \
-       if git show-ref --verify refs/heads/$${mc} > /dev/null 2>&1; \
+       if git ls-remote --heads --exit-code git@github.com:celo-org/celo-monorepo.git $${mc} > /dev/null 2>&1; \
        then \
                echo "Expected commit hash or tag in 'monorepo_commit' instead found branch name '$${mc}'"; \
                exit 1; \
```

@gastonponti Should I apply this and switch the monorepo_commit from the branch name to the corresponding commit hash, or do you prefer keeping the branch?

**Comment by piersy** [comment]
A thought I had related to this is that it might make more sense to checkout a separate monorepo for each commit, (so include the commit hash in the checked out folder name) that would switching back and forth between multiple monorepo versions much quicker and easier. It's not something that happens that often, but when we are close to a boundary between to core contract versions it is a bit painful to do the switching.

**Comment by karlb** [comment]
> it might make more sense to checkout a separate monorepo for each commit

That would be easy enough to do, it would just leave a rather big checkout for each of the commits.
```
% du -sh ../.celo-blockchain-monorepo-checkout
2.0G	../.celo-blockchain-monorepo-checkout
```

**Comment by gastonponti** [comment]
> @gastonponti Should I apply this and switch the monorepo_commit from the branch name to the corresponding commit hash, or do you prefer keeping the branch?

It's a weird call. This is the correct way, but on the other hand it will make it less readable. I prefer the commit one because it will assure that everyone is in the same page, but at the cost of having to search for that commit to understand which version are we pointing.

I would add this, but I'll let you decide it

**Comment by karlb** [comment]
Ok, I added the no-branch limitation and the one-checkout-per-monorepo-commit suggestion in https://github.com/celo-org/celo-blockchain/pull/2041.
