### ISSUE TITLE
Backport the go-ethereum go-native tracer

### ISSUE THREAD

**Issue by palango** [celo-org/celo-blockchain#1970]
As requested in https://github.com/celo-org/celo-blockchain/issues/1942#issuecomment-1277095805

@jsvisa Pulling this request in its own issue.

# Rationale

Improve performance of tracing.

# Implementation

-

**Comment by jsvisa** [comment]
Yeah, I'll implement it asap

**Comment by palango** [comment]
> Yeah, I'll implement it asap

@jsvisa It would be great if you find the time to create a PR for this.

**Comment by carterqw2** [comment]
Gonna test with Blockscout on staging.

**Comment by palango** [comment]
Resolved in https://github.com/celo-org/celo-blockchain/pull/2137
