### ISSUE TITLE
"insufficient funds for gas" error when doing debug_traceBlockByNumber on 0x108F49C

### ISSUE THREAD

**Issue by quick-pawiromitchel** [celo-org/celo-blockchain#2002]
## Description
When running `debug_traceBlockByNumber` on block `0x108F49C` results in a `insufficient funds for gas` error

https://celoscan.io/block/17364124

## Current Behavior

Running the following request
```
{
    "method": "debug_traceBlockByNumber",
    "params": [
        "0x108F49C",
        {
            "tracer": "callTracer"
        }
    ],
    "id": 1,
    "jsonrpc": "2.0"
}
```

Results in this error
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "insufficient funds for gas * price + value + gatewayFee: address 0xBF4D711071Cd9c0402387DeCDD53d3babDb82Bf6 have 1702475464032708 want 1710879300000000"
    }
}
```

Celo client version: `v1.7.2`
OS: Linux

**Comment by palango** [comment]
Hi @quick-pawiromitchel . Thanks for reporting this.

I successfully reproduced this and it might be related to gas calculation in the tracing module.
