### ISSUE TITLE
Failed to deploy to Graph node : network not supported by registrar: no network celo-alfajores found on chain ethereum

### ISSUE THREAD

**Issue by umesh-spirinova** [celo-org/celo-blockchain#2027]
I am trying to deploy subgraph for alfajores. Here is a snippet of subgraph.yaml file - 

dataSources:
  - kind: ethereum/contract
    name: ERC721Factory
    network: celo-alfajores
    source:
      address: '0x98679D582AB3398C03D3308dEB9c7AeC50B52ded'
      abi: ERC721Factory
      startBlock: 16422659
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      file: ./src/mappings/erc721Factory.ts
      entities:
        - ERC721Factory
      abis:
        - name: ERC721Factory
          file: ./node_modules/@oceanprotocol/contracts/artifacts/contracts/ERC721Factory.sol/ERC721Factory.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: NFTCreated(address,indexed address,string,indexed address,string,string,bool,indexed address)
          handler: handleNftCreated
        - event: TokenCreated(indexed address,indexed address,string,string,uint256,address)
          handler: handleNewToken

  - kind: ethereum/contract
    name: FactoryRouter
    network: celo-alfajores
    source:
      address: '0xc37F8341Ac6e4a94538302bCd4d49Cf0852D30C0'
      abi: FactoryRouter
      startBlock: 16422659
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript

But when I try to deploy using graph deploy it gives the following error - 
Failed to deploy to Graph node : network not supported by registrar: no network celo-alfajores found on chain ethereum

I tried using alfajores,  celo-alfajores, celoalfajores for network name.

**Comment by carterqw2** [comment]
This is the repo for the Celo blockchain client, the issue you're describing is related to a graph deployment.

Please try following the [guide](https://docs.celo.org/blog/using-the-graph) or if you can't find your answers there, you could try asking around on [Discord](https://discord.gg/celo).
