### ISSUE TITLE
Crypto question abount EIP-2539

### ISSUE THREAD

**Issue by hujw77** [celo-org/celo-blockchain#2059]
## Expected Behavior
https://eips.ethereum.org/EIPS/eip-2539#test-cases
> Multiplication by the unnormalized scalar (scalar + group_order) * P = scalar * P

For `Multiexponentiation`, I add the code below to check the property.
https://github.com/celo-org/celo-blockchain/blob/ebd771d4c414567517974d4a006a2f39e2b7e38c/core/vm/contracts.go#L1851
```diff
// bls12377 Main subgroup order = 0x12ab655e9a2ca55660b44d1e5c37b00159aa76fed00000010a11800000000001
// let scalar % group_order
+ m := new(big.Int).SetBytes(common.FromHex("0x12ab655e9a2ca55660b44d1e5c37b00159aa76fed00000010a11800000000001"))
+ scalars[i] = new(big.Int).Mod(scalars[i], m)
```
I think the result should be the same.
```sh
go test ./ -v -run TestPrecompiledBLS12377G1ZMultiExp

--- FAIL: TestPrecompiledBLS12377G1ZMultiExp (0.43s)
...
```
But the test cases failed.

```diff
- Compute r0 = e_0 * p_0 + e_1 * p_1 + ... + e_(k-1) * p_(k-1)
+ Compute r1 = (e_0 % group_order) * p_0 + (e_1 % group_order) * p_1 + ... + (e_(k-1) % group_order) * p_(k-1)
```

But the result `r0 != r1`

Code branch: `master`

**Comment by hujw77** [comment]
@kilic @prestwich I look into this PR  https://github.com/celo-org/celo-blockchain/pull/1157 
> Zexe test vectors are generated with https://github.com/kilic/zexe/blob/eip2539/algebra/src/bls12_377/curves/eip2539_test.rs
> Matter test vectors are generated with https://github.com/kilic/eip1962-1/tree/celo1157/src/public_interface/celo1157

I notice Zexe test vectors are generated from [Fr](https://github.com/kilic/zexe/blob/079ecae40b1bda29a890b3760b6bcef81ee97817/algebra/src/bls12_377/curves/eip2539_test.rs#L271)
 and Matter test vectors are genrated from [u64,4]. https://github.com/kilic/eip1962-1/blob/65bc07b37af300dcd4bf9a87961b0d7c0f4cb1d6/src/public_interface/celo1157/mod.rs#L898
There are generated from different rand range.

Please give me some pointers about my question.

**Comment by palango** [comment]
@hujw77 Thanks for reporting this.

Those precompiles are removed in the Celo Gingerbread hardfork which will go live later today. For the reasoning behind this see https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0063.md.

Closing this issue for that reason.
