### ISSUE TITLE
hardhat --fork no longer working with Celo

### ISSUE THREAD

**Issue by sirpy** [celo-org/celo-blockchain#2080]
Has the celo nodes gone through some upgrade recently? that changed the data form?

## Expected Behavior

being able to run a simulated fork of celo

## Actual Behavior

Error HH604: Error running JSON-RPC server: Invalid JSON-RPC response's result.

Errors: Invalid value undefined supplied to : RpcBlockWithTransactions | null/sha3Uncles: HASH, Invalid value undefined supplied to : RpcBlockWithTransactions | null/difficulty: QUANTITY, Invalid value undefined supplied to : RpcBlockWithTransactions | null/uncles: HASH Array

## Steps to reproduce the behavior
npx hardhat node --fork https://forno.celo.org

**Comment by pahor167** [comment]
Possible workaround is to use Anvil from Foundry

anvil --fork-url https://forno.celo.org

**Comment by sirpy** [comment]
@palango not sure

**Comment by sirpy** [comment]
seems to be working now
