### ISSUE TITLE
getTransactionReceipt is returning empty result.

### ISSUE THREAD

**Issue by etkim7** [celo-org/celo-blockchain#2126]
This issue is related to https://github.com/celo-org/celo-blockchain/issues/1998
As I can't open the issue, I created new one with additional info.

## Description

getTransactionReceipt is returning empty result
e.g.) 0x8a6f0fd69b851207d69e3d7f0d58e476b5ceed655229c8301e391760ad5b6d09 txid

## Current Behavior

the result is null for this api call.

## Context

getTransactionReceipt is critical part for checking the transaction's call result.

The code worked well before but it suddenly stopped working due to this change.
https://explorer.celo.org/mainnet/block/12830952/transactions

I already compiled to latest one and tried but no luck.
Currently I'm running `celo/v1.7.2-stable-7e0f8162/linux-amd64/go1.19.4`

![image](https://user-images.githubusercontent.com/33079832/212458694-05409007-2ddc-4607-8fd2-4b4197dee3b4.png)

--
Update 2023.06.09

Still problem is not fixed
I updated to celo/v1.7.4-stable-3a6e0006/linux-amd64/go1.20.4
and synced from scratch but this problem still exists
![image](https://github.com/celo-org/celo-blockchain/assets/33079832/068951a6-ce3d-4ddb-99cd-700ac7f05dfc)

```
http http://127.0.0.1:15122 jsonrpc=2.0 id=0 method=eth_getTransactionReceipt params:='["0x8a6f0fd69b851207d69e3d7f0d58e476b5ceed655229c8301e391760ad5b6d09"]'
```
```
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 63
Content-Type: application/json
Date: Fri, 09 Jun 2023 09:41:49 GMT

{
    "id": "0",
    "jsonrpc": "2.0",
    "result": null
}
```

Is there anyway that to get well working snapshot or proven binary version?

seems like this issue is also related.
https://github.com/celo-org/celo-blockchain/issues/2014

**Comment by palango** [comment]
Thanks for testing this again. I just checked with forno and the result is returned there, so this seems to be an issue with your setup.

Do you still have the logs from the syn?
I also see that you're using go 1.20. We don't do any testing on that version and recommend using go 1.18 for now. Any chance you can try with that version?


btw., you could have reopened the old issue to continue the discussion there.

**Comment by etkim7** [comment]
Here's the latest log.
I think it's just plain normal logs. The block number matches to block explorer.
```
INFO [06-09|10:25:14.673] Unindexed transactions                   blocks=1    txs=47    tail=17,377,613 elapsed="521.556µs"
INFO [06-09|10:25:19.627] Imported new chain segment               blocks=1    txs=6     mgas=1.200   elapsed=32.151ms    mgasps=37.330  number=19,727,613 hash=d02207..000737 dirty=104.58MiB
INFO [06-09|10:25:19.627] Unindexed transactions                   blocks=1    txs=9     tail=17,377,614 elapsed="232.483µs"
INFO [06-09|10:25:24.610] Imported new chain segment               blocks=1    txs=13    mgas=1.710   elapsed=36.602ms    mgasps=46.730  number=19,727,614 hash=b6442e..a6ec45 dirty=104.63MiB
INFO [06-09|10:25:24.610] Unindexed transactions                   blocks=1    txs=19    tail=17,377,615 elapsed="508.687µs"
INFO [06-09|10:25:29.580] Imported new chain segment               blocks=1    txs=7     mgas=0.743   elapsed=27.895ms    mgasps=26.631  number=19,727,615 hash=2d5717..c72fc0 dirty=104.58MiB
INFO [06-09|10:25:29.580] Unindexed transactions                   blocks=1    txs=31    tail=17,377,616 elapsed="518.427µs"
INFO [06-09|10:25:33.229] Deep froze chain segment                 blocks=12   elapsed=33.688ms    number=19,637,615 hash=4c9eca..4ff72b
INFO [06-09|10:25:34.680] Imported new chain segment               blocks=1    txs=13    mgas=1.998   elapsed=40.713ms    mgasps=49.069  number=19,727,616 hash=436504..f96fd2 dirty=104.55MiB
INFO [06-09|10:25:34.680] Unindexed transactions                   blocks=1    txs=24    tail=17,377,617 elapsed="486.976µs"
INFO [06-09|10:25:39.686] Imported new chain segment               blocks=1    txs=14    mgas=2.058   elapsed=37.739ms    mgasps=54.522  number=19,727,617 hash=4ab7c5..75e888 dirty=104.49MiB
INFO [06-09|10:25:39.687] Unindexed transactions                   blocks=1    txs=18    tail=17,377,618 elapsed="650.609µs"
INFO [06-09|10:25:44.589] Imported new chain segment               blocks=1    txs=14    mgas=1.940   elapsed=39.895ms    mgasps=48.632  number=19,727,618 hash=6ad324..dedb83 dirty=104.48MiB
INFO [06-09|10:25:44.589] Unindexed transactions                   blocks=1    txs=9     tail=17,377,619 elapsed="136.591µs"
```

I can recompile and try with go 1.18 / celo-1.7.4
maybe I need to resync from scratch again.


I believe I can't reopen the issue if moderator closed that. My previous issue
https://github.com/celo-org/celo-blockchain/issues/1998 doesn't show me "open" button

**Comment by etkim7** [comment]
Tried with `instance=celo/v1.7.4-stable-3a6e0006/linux-amd64/go1.18.10`
but the txid receipt result is still null
![image](https://github.com/celo-org/celo-blockchain/assets/33079832/152ff12a-3488-4a50-9bd9-653f7b05353c)

I can get normal output when I try recent transaction
`http http://127.0.0.1:15122 jsonrpc=2.0 id=0 method=eth_getTransactionReceipt params:='["0x402c9a5cfa3f8b170936f479159ad06ff214306c87822aefb41fcd4b9f8c282f"]'`

Seems like something's wrong with past blockchain processing

Any suggestions?

**Comment by palango** [comment]
@etkim7 Likely you need to sync the whole chain with the correct go version.

Alternatively you can use a snapshot found [here](https://www.snapshot.directory/networks/celo) to avoid having to resync the whole chain. Please try this out, but only with the node running on go 1.18 or 1.19.

**Comment by etkim7** [comment]
@palango I actually synced from scratch after the new build.
I tried syncing from scratch with old go version and latest go version both.
I believe it is reproducible if others are syncing from scratch with latest celo build.

**Comment by palango** [comment]
@etkim7 You mean that you used `master` for syncing?

Please use the released versions when you want to run a node, as there might be problems in the development version. The one you ran into is probably https://github.com/celo-org/celo-blockchain/issues/2132

**Comment by etkim7** [comment]
well I compiled the latest release version. I don't use `master` branch usually.
my synced `~/.celo/celo` directory's disk size is 94GB, while the snapshot's `~/.celo/celo` is 154GB

Maybe this would be helpful?

![image](https://github.com/celo-org/celo-blockchain/assets/33079832/168d38b1-045a-4ef5-bd90-240581def2d3)

**Comment by etkim7** [comment]
Same error happens though I synced from snapshot.
``` http http://127.0.0.1:11122 jsonrpc=2.0 id=0 method=eth_getTransactionReceipt params:='["0x8a6f0fd69b851207d69e3d7f0d58e476b5ceed655229c8301e391760ad5b6d09"]'```
![image](https://github.com/celo-org/celo-blockchain/assets/33079832/b7e974af-1f5d-4c6c-940f-3603db693fac)

Weird thing is that I can retrieve correct information from latest transactions. Only some range of old transactions are missing.

**Comment by palango** [comment]
> my synced `~/.celo/celo` directory's disk size is 94GB, while the snapshot's `~/.celo/celo` is 154GB

This is weird, can you please post the options that you pass when starting geth?



> Weird thing is that I can retrieve correct information from latest transactions. Only some range of old transactions are missing.

How big is the harddrive you're using? Maybe it's related to pruning? See 
https://geth.ethereum.org/docs/fundamentals/pruning

**Comment by jun0tpyrc** [comment]
hitting same things 


@palango  
0x3da7ef2d35251f92dcc20988ef0d6ee66cf5b05f2ad0556cfc6cff52104593fd
https://explorer.celo.org/mainnet/tx/0x3da7ef2d35251f92dcc20988ef0d6ee66cf5b05f2ad0556cfc6cff52104593fd

0x88e872a13807b296c5af63940f5d0b0a98a09b4754ca85fd31b31c155e94aa0f
https://explorer.celo.org/mainnet/block/0x88e872a13807b296c5af63940f5d0b0a98a09b4754ca85fd31b31c155e94aa0f/transactions

these are some examples - can't even get on any rpc for  `eth_getTransactionByHash / eth_getTransactionReceipt` but in explorer,  maybe also the nodes from public snapshot - possible to investigate &/ get a data-patched/working datadir? 🙏 

https://chainlist.org/chain/42220
https://www.alchemy.com/chain-connect/endpoints/celo-celo-mainnet

**Comment by jun0tpyrc** [comment]
also , seems public snapshot is pruned so we don't have some old txs result from 

https://celo.api.onfinality.io/public
https://1rpc.io/celo
no have 0x3da7ef2d35251f92dcc20988ef0d6ee66cf5b05f2ad0556cfc6cff52104593fd, 0x92bf47ecfa16ff3597e84f7e15e4866169ac019c3b4e654136cdbd71d226acca
https://forno.celo.org
have
0x3da7ef2d35251f92dcc20988ef0d6ee66cf5b05f2ad0556cfc6cff52104593fd, 0x92bf47ecfa16ff3597e84f7e15e4866169ac019c3b4e654136cdbd71d226acca

**Comment by jcortejoso** [comment]
Hi @jun0tpyrc, I've just tried with the snapshot from [this link](https://storage.googleapis.com/celo-chain-backup/mainnet/chaindata-latest.tar.zst) and it seems both tx receipts are available:

```
user@mainnet-daily-chain-backup-test:/# curl --request POST --url https://forno.celo.org --header 'accept: application/json' --header 'content-type: application/json' --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": [
    "0x8a6f0fd69b851207d69e3d7f0d58e476b5ceed655229c8301e391760ad5b6d09"
  ]
}
'
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x7d125d95145b8acecb082116ec59ae89b15353e18bb5e608765e88e837378f4f","blockNumber":"0xc3c8ca",...,"type":"0x0"}}
user@mainnet-daily-chain-backup-test:/# curl --request POST \
     --url https://forno.celo.org \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "eth_getTransactionReceipt",
  "params": [
    "0x92bf47ecfa16ff3597e84f7e15e4866169ac019c3b4e654136cdbd71d226acca"
  ]
}
'
{"jsonrpc":"2.0","id":1,"result":{"blockHash":"0x88e872a13807b296c5af63940f5d0b0a98a09b4754ca85fd31b31c155e94aa0f","blockNumber":"0x131c11e",...}}
```

**Comment by jun0tpyrc** [comment]
seem right ,thanks for verification

for other's notes : i think i was confused by the default ` --txlookuplimit value (default: 2350000)` inherited - that does pruning soon after node started
