### ISSUE TITLE
Full nodes drop transactions below minimum fee

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#214]
### Expected Behavior

Full nodes set and share the minimum fee value below which they will accept transactions (along with their etherbase), light clients set fee to 1.x times this value. Light clients reject txs that specify a fee lower than any of their peers are willing to accept

### Current Behavior

Light clients don't know anything about their peers' fee prices

**Comment by nategraf** [comment]
The gas fee sharing mechanism referenced here was replaced, and this feature was implemented by gateway fee checking in the les server handler.
