### ISSUE TITLE
Title: Issue with tx.gasprice method on Celo Testnet

### ISSUE THREAD

**Issue by amit-supraoracles** [celo-org/celo-blockchain#2162]
Hello Celo,

I need help with the **tx.gasprice** method in REMIX IDE on Celo Testnet.
The gas price returned seems incorrect or unavailable when deploying and executing a contract
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

contract GasConract {
    uint256 public gasPriceData;
    function setGasPrice() public {
        gasPriceData = tx.gasprice;
    }
}
```
Any insights or solutions would be appreciated.

Thank you,
Amit Kumar
[SupraOracles](https://supraoracles.com/)

**Comment by palango** [comment]
Hi @amit-supraoracles 
Could you please provide some additional information:
- Which testnet are you using and do you use a local node or forno?
- Do you have a link on the chain explorer for the failing transaction?
- What are the actual and expected values?

**Comment by amit-supraoracles** [comment]
Thanks @palango but seems like it is working now !!
