### ISSUE TITLE
Celo rosetta node issue

### ISSUE THREAD

**Issue by Swornatoya** [celo-org/celo-blockchain#2222]
The celo rosetta node had stopped, when we tried starting it again  getting the below error. Could you please help resolve this

`Executing: /usr/local/bin/geth --datadir /data/celo --nousb --http --http.addr localhost --http.port 8545 --http.vhosts localhost --syncmode full --gcmode archive --http.api eth,net,web3,debug,admin,personal --ipcpath /var/geth.ipc --light.serve 0 --light.maxpeers 0 --maxpeers 1100 --consoleformat term --txlookuplimit 0 --port 30303 --verbosity 3 --cache 1024
ERROR[01-19|13:24:35.751] Rosetta run failed                       err="Geth service did not create ipc file within deadline, check the log: /logs/celo.log"`

@eelanagaraj : Could you please help us with the above issue

**Comment by palango** [comment]
@Swornatoya Are you still running into this issue?

**Comment by Swornatoya** [comment]
@palango : This has been resolved. Thanks
