### ISSUE TITLE
Node stop syncing with BAD BLOCK

### ISSUE THREAD

**Issue by chuwt** [celo-org/celo-blockchain#2325]
Failed to call core contract.

<img width="1344" alt="截屏2024-08-08 15 24 04" src="https://github.com/user-attachments/assets/52056197-62cd-4d36-bcbb-707c8d0e4951">

**Comment by chuwt** [comment]
@palango An existing node, the version is v1.8.2, got this error yesterday.

**Comment by palango** [comment]
@chuwt We don't see this on our internal nodes, so our guess is that your state has become corrupted. Could you try syncing from a backup?

**Comment by chuwt** [comment]
Okay. BTW, do we have an archive snapshot?
