### ISSUE TITLE
Archive node issue

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-blockchain#2328]
```
Hi team after serving request a while 

We would the archive node came across the sync issue

Here is our log 
Could you help us to figure out what's wrong with?
```

**Comment by carterqw2** [comment]
Here is the log file:

[celo.txt](https://github.com/user-attachments/files/16846777/celo.txt)

**Comment by jcortejoso** [comment]
It seems there are some tcp connection issues that ends ups restarting the peering connections. Do you know the version of celo-blockchain using?
Also it could be interesting to check if the kernel is closing connections (i.e: `netstat -an | grep -i tcp`)
