### ISSUE TITLE
Expose GasPriceMinimum functions in RPC

### ISSUE THREAD

**Issue by jarmg** [celo-org/celo-blockchain#304]
### Expected Behavior
We have added `api_backend` functions 
- `SuggestPriceInCurrency`
- `GasPriceMinimum`
- `InfrastructureFraction`
And we should should expose these through the rpc for the light client and full node

### Current Behavior
They are not exposed

**Comment by mcortesi** [comment]
We've already have `SuggestGastPriceMinimun` with support for multiple currencies. The rest are deprioritized
