### ISSUE TITLE
Ensure that the discovery protocol uses from.msg.IP throughout

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#314]
### Expected Behavior

When a node is communicating with another via the discovery prototol, it should now use the from.msg.IP field for the remote node's IP (instead of the udp source IP).

### Current Behavior

The from.msg.IP is used when handling pings, but perhaps not for all the messages types.

**Comment by timmoreton** [comment]
Won't need if we are going to revert discovery src ip change.
