### ISSUE TITLE
Eth nodes SNBAT find Celo nodes

### ISSUE THREAD

**Issue by jarmg** [celo-org/celo-blockchain#361]
### Expected Behavior
We do not want eth nodes to pollute Celo routing tables. 

### Current Behavior
We believe that eth nodes are polluting Celo routing tables. 

### Initial implementation ideas
The first idea on doing this is to perform some capability or protocol resolution in discovery (while this resolution is normally done in peer negotiation).

**Comment by kevjue** [comment]
The plan is to modify the discovery "ping" message to contain a "network_id" field.   All nodes (including the bootnode) will fill this field in with the network_id they are using and will only process ping messages with their network_id.  This will result in having nodes only adding enode urls that have the same network id into their discovery tables.
