### ISSUE TITLE
Findnode failed errors in p2p discovery

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-blockchain#363]
### Expected Behavior

No findnode failures if a node receives a neighbors packet in response to a findnode packet before timing out.

### Current Behavior

When a node sends a findnode packet and receives a neighbors packet in response, the node treats the findnode packet as timed out. This results in an error: `{"err":"RPC timeout","failcount":26,"id":"3298d60897ca6e0ac470e87a0583bc2c09ba66e2f3a656f100d4c1f6ff502cb7","msg":"Findnode failed","severity":"debug","timestamp":"2019-07-23T23:24:05.002148491Z"}` *every* time a findnode is sent out. The failcount for a particular peer id keeps climbing.

I did some digging with logs on a branch: https://github.com/celo-org/celo-blockchain/tree/trevor/internal-bn-debugging

This confirmed that a node still believes a sent findnode packet to not have received a neighbors response, despite actually receiving one.

The two prevailing theories:
1. In this check https://github.com/celo-org/celo-blockchain/blob/7b36a7827a26697fded91c8a2468282f75f3261d/p2p/discover/udp.go#L476, the times are only precise to the level of seconds. Line 477 after that prints:
```
{"msg":"trevor: in timeout loop","now":"2019-07-23T23:24:07+0000","pDeadline":"2019-07-23T23:24:07+0000","pFrom":"cf4a98132ef51cfb599912bdea4252d285ca6c74eec1fb5b5735c1e522a9414b","pIp":"10.0.1.103","pptype":4,"severity":"debug","timestamp":"2019-07-23T23:24:07.007037262Z"}
```
However, this may just be because of poor precision when printing.
2. https://github.com/celo-org/celo-blockchain/blob/7b36a7827a26697fded91c8a2468282f75f3261d/p2p/discover/udp.go#L422 is not reached when a neighbors packet is received

Note: this may be related to Nam's UDP change, but it's unknown

**Comment by oneeman** [comment]
I'm not seeing this on master.  I added some logging to see what's happening and found that:

1. The vast majority of findnodes succeed and don't give `RPC timeout`
2. For the ones that do give timeouts, no replies had been received

I'm going to close this.  @tkporter If you still have locally the branch with the debugging changes and can try them or similar changes on master and still see this, reopen and let me know.
