### ISSUE TITLE
Docker doesn't allow interactive passphrase input on `account new`

### ISSUE THREAD

**Issue by winslyn** [celo-org/celo-blockchain#364]
### Expected Behavior

```
$ docker run -v `pwd`:/root/.celo -it us.gcr.io/celo-testnet/celo-node:alfajores account new
```

It will prompt you for a passphrase, ask you to confirm it.

### Current Behavior

```
$ docker run -v `pwd`:/root/.celo -it us.gcr.io/celo-testnet/celo-node:alfajores account new
Your new account is locked with a password. Please give a password. Do not forget this password.
Fatal: Failed to read passphrase: liner: function not supported in this terminal
```

It doesn't allow me to enter a passphrase.

```
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-54-generic x86_64)
Docker version 19.03.1, build 74b1e89
Node v10.16.0
```

**Comment by nambrot** [comment]
Thank you for your interest and creating the issue. What shell/terminal are you using?

**Comment by winslyn** [comment]
I am using bash on iTerm2.

**Comment by winslyn** [comment]
well, it seems a reboot solved the problem.

**Comment by daithi-coombes** [comment]
I'm getting this issue on `ubuntu 18.04`. Both with `--password passwordFile` and without the pswd flag are returning the same...

Docker version: `19.03.1`

```
Fatal: Failed to read passphrase: liner: function not supported in this terminal
```

Seems error is from `geth`: https://ethereum.stackexchange.com/questions/28862/liner-function-not-supported-in-this-terminal-when-doing-personal-newaccount

Odd thing is its working locally. I'm using instructions to install directly from here: https://docs.celo.org/getting-started/running-a-validator

**Comment by daithi-coombes** [comment]
I can confirm that this issue is random. On my local machine, creating a new user worked 2 out of 5 goes and on the remote it returned the above get error until I rebooted. Below is output of latest gamble.

Returned error is a `geth` error and should be fixed afaik. So am thinking that some race condition building geth commands could be the cause? You can see below that one `account new` worked but the next call didn't, both without the `--password` flag but issue persists randomly with it.

`docker 19.03`, remote:`ubuntu 18.04`, local:`mac osx10.14.6`

```
$ docker run -v `pwd`:/root/.celo -it us.gcr.io/celo-testnet/celo-node:alfajores account new
INFO [09-02|22:22:12.578] Maximum peer count                       ETH=25 LES=0 total=25
Your new account is locked with a password. Please give a password. Do not forget this password.
Passphrase: 
Repeat passphrase: 
Address: {b51c08465dc134735a415a0482ebcf4d022718b4}

minime@celo-testnet-node0:~/bc-stake-celo$ docker run -v `pwd`:/root/.celo -it us.gcr.io/celo-testnet/celo-node:alfajores account new
INFO [09-02|22:24:31.544] Maximum peer count                       ETH=25 LES=0 total=25
Your new account is locked with a password. Please give a password. Do not forget this password.
Fatal: Failed to read passphrase: liner: function not supported in this terminal
stillminime@celo-testnet-node0:~/bc-stake-celo$
```

@winslyn think this issue persists?

**Comment by daithi-coombes** [comment]
So quick fix is: jump into container shell and run commands from there...

```
docker run -v `pwd`:/root/.celo -it --entrypoint /bin/sh us.gcr.io/celo-testnet/celo-node:alfajores
```

Then run setup commands against `geth`, eg:
```
geth account new
```

**Comment by timmoreton** [comment]
The docs for master describe this workaround -- https://docs.celo.org/v/master/getting-started/running-a-validator -- please let me know how you get on 

we are beginning to think about how to implement a richer CLI/REPL experience for validators, including possibly bringing functionality into the 'geth attach' REPL or moving it out to a REPL based around our CLI.  We probably won't start the work for a couple of weeks but appreciate your suggestions/feedback!

Issue is #353

**Comment by daithi-coombes** [comment]
... also found these instructions to work: https://medium.com/simply-vc/a-step-by-step-guide-to-joining-the-celo-testnet-e45b0c523a78

(basically run `geth` commands from within the container)
