### ISSUE TITLE
Internal EVM calls SBAT emit events

### ISSUE THREAD

**Issue by m-chrzan** [celo-org/celo-blockchain#370]
### Expected Behavior

If the inflation factor gets updated when calling `debitFrom` to pay for a transaction fee with Celo Dollars, an `InflationFactorUpdated` event should be emitted.

### Current Behavior

Haven't checked 100%, but from what I've seen, events from internal EVM calls are likely to be lost. So first step is to confirm this is actually a problem, but wanted to flag this.

**Comment by mrsmkl** [comment]
Tested by adding an event that is emitted every time `debitFrom` is called. It shows up in the receipts. Looks like events are added to statedb similarly to changes made into storage.

**Comment by mrsmkl** [comment]
If there is no associated transaction, the logs will then be gone...
