### ISSUE TITLE
Everyone SBAT reference more detailed README

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#390]
### Expected Behavior

README makes it easy to jump into the codebase

This is part of epic:  https://github.com/celo-org/celo-blockchain/issues/1012

### Current Behavior

Not so easy to jump into the codebase

**Comment by jeamick** [comment]
Hello @asaj,

If not taken I would like to help on this one(if possible):

Do you think that having a small part about the difference from the Geth codebase with the particular parts of the repository could be interesting to add ?

Thanks
JM
