### ISSUE TITLE
Light clients SBAT send transactions to multiple full nodes

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#392]
### Expected Behavior

Light clients create N copies of a transaction with N gasFeeRecipients, and send those N transactions to N peers
 
### Current Behavior

Send the transaction to a single, random, peer

**Comment by silasbw** [comment]
Is this the desired SBAT?

> A light client SBAT reliably announce a transaction via a full node.

(and one potential implementation path is to send N transactions to N different full nodes, and another potential implementation _might_ involve retries)
