### ISSUE TITLE
Validators SBAT recover consensus state on restart

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#396]
### Expected Behavior

Make Istanbul crash consistent. PBFT relies on a node persisting its progress through a round (i.e has it sent a prepare).  

### Current Behavior

Behavior if a validator node restarts and rejoins a consensus round that it already participated in is undefined.

**Comment by ashishb** [comment]
#520 merged. This issue can be closed as soon as #531 is merged in.

**Comment by mcortesi** [comment]
Solved on #632
