### ISSUE TITLE
Light Clients SBAT to connect to nodes on the same network

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-blockchain#40]
### Expected Behavior

When multiple light clients are on the same network, they should still be able to connect to the same node.

### Current Behavior,

Due to https://github.com/ethereum/go-ethereum/pull/16899#issuecomment-418513423, currently light clients cannot have the same IP address

### Current workaround

We made a modification in #41 to change the identification of a peer by IP address to their enode address. This loosens our ability to actually identify badly behaving clients but allows us to continue to use our Kubernetes setup as well as have multiple light clients on the same network.

**Comment by mcortesi** [comment]
The current workaround is considered enough.

For the future, we might consider working on spam protection
