### ISSUE TITLE
Users SBAT know easily when node is synced

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#419]
### Expected Behavior

* Clear log message showing when a sync is complete
* Get rid of other spurious log messages
* Update full node and validator tutorials to say you need to wait for that log message before finishing (full node) or proceeding to register as a validator. 

### Current Behavior

Hard to know when sync is done. Unclear when to proceed in tutorial.

**Comment by cla-bel** [comment]
Duplicate issue: https://github.com/celo-org/celo-monorepo/issues/714
