### ISSUE TITLE
Users SBAT send sequence of txs in sequential blocks

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#420]
### Expected Behavior

A web3 client waiting for a tx to get included in a block should be notified early enough that a subsequent transaction can land in the very next block.

### Current Behavior

We see gaps between transactions during migrations and regular use

e.g https://alfajores-blockscout.celo-testnet.org/address/0xcea3ef8e187490a9d85a1849d98412e5d27d1bb3/transactions?block_number=174320&index=0

**Comment by asaj** [comment]
I didn't dig too deeply, but one thing I noticed when playing around in celo-blockchain is that as soon as block N is finalized, validators create block N+1 with a timestamp in the future, and wait around until that timestamp to send the preprepare.

This suggests that the earliest any tx sent between the finalization of block N and the preprepare for N+1 can be included is N+2, adding an arguably unnecessary 1 block latency.
