### ISSUE TITLE
Discovery protocol SNBAT extract the sender's IP from the ping packet

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#444]
### Expected Behavior

The discovery protocol doesn't use the sender's IP address from within the ping packet, and uses the udp's `from` field.

### Current Behavior

The discovery protocol extract's the sender's IP from within the ping packet.

We initially had to make this change for Alfajores since the nodes within the testnets had to be accessible on the internet.   However, there are a number of places within the p2p/discovery/udp.go that assumes that the udps` `from` field is the actual ip address of the node (as opposed to the ip address of the load balancer in front of the node).  This is resulting in some odd behavior at the discovery level (e.g. enodes are kicked off of the discovery table and seeing RPC timeouts).

**Comment by oneeman** [comment]
This is the PR which made the change: https://github.com/celo-org/celo-blockchain/pull/301
