### ISSUE TITLE
Validators SBAT submit their BLS signed ethereum address as proof-of-possession 

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#449]
### Expected Behavior

Validators prove possession of their private key by signing their ethereum address

### Current Behavior

Validators prove possession of their private key by signing their BLS public key

**Comment by kobigurk** [comment]
@nvesely looked at the theoretical side and it seems to be a good way. I added support for this in the latest `bls-zexe`, so it's a matter of wiring it up.
The idea is that either @kevjue or I will pick it up in the next week or two.
