### ISSUE TITLE
Block proposers SBAT include signatures for the previous block

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#456]
### Expected Behavior

Block proposers should include signatures seen for the previous block in the block body. This issue can be broken down to the following tasks:

- [x] Previous signatures (and signer bit vector) should be added to the Block struct.
- [x] Clients should validate signatures when processing a block by checking that the aggregated signature matches the aggregated public key of the previous block. This can be tricky at the epoch boundary as the previous block's validator set may not be easily known (e.g. after a fast sync). It may have to be inferred from the validator diff in the header.
- [ ] This (and past) signatures and bit vectors should be stored in a smart contract so that they can be accessed by other contracts (API for other smart contracts are TBD).

### Current Behavior

Not included

**Comment by m-chrzan** [comment]
Some first steps for including the parent block seal in the block on `m-chrzan/parent-seal` branch.
