### ISSUE TITLE
Ethstats operator SBAT block stats submission on a per-node basis

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#459]
* TLS proxy
* Token based auth
* Figure out best approach to integrate this with 'elected validators' in #458 - maybe they get a single global token.

**Comment by diminator** [comment]
With the changes made for #458, operators have a "trusted" list of nodes that they accept upon authorization. Stats are also signed for non-repudiation. However, there's no handshake protocol, so nodes could sniff and re-submit packages of trusted nodes. This would allow them to occupy a connection, but they won't be able to change the signed content

There's a "blocked" list in the ethstats operator, that can hold IP addresses.
