### ISSUE TITLE
Users SBAT to reveal their phone number without sending a transaction

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#46]
### Expected Behavior

Users SBAT send their encrypted phone number to the target verifier node without sending a transaction, via whisper or the gossip protocol.

### Current Behavior

Users send their encrypted phone number via a transaction, which is then run by the verifier node when the block is mined.

**Comment by mcortesi** [comment]
@asaj closing this. 
Reopen if you disagree

**Comment by nambrot** [comment]
Wow #throwback
