### ISSUE TITLE
Users SBAT see blocks left in epoch on ethstats

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#463]
* Number of blocks remaining in epoch in a big box
* Total blocks in epoch just below it

**Comment by diminator** [comment]
@timmoreton does this layout correspond to design?

![celostats](https://user-images.githubusercontent.com/6178597/65442761-16dd3080-de2d-11e9-8913-865a3ee05e78.gif)

**Comment by diminator** [comment]
A more compact version:
![celostats-compac](https://user-images.githubusercontent.com/6178597/65444337-1eea9f80-de30-11e9-83e4-914c0a62814a.gif)

**Comment by timmoreton** [comment]
Awesome! not sure you're covering it in this ticket but would be great to change "Last blocks miners" to "Last validators"
