### ISSUE TITLE
Users SNBAT see PoW info on ethstats

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#464]
Remove these:
- [ ] Uncles box
- [ ] Avg Network hash rate box
- [ ] Difficulty box
- [ ] Difficulty graph
- [ ] Uncle count graph
- [ ] "Attention! This page does not represent .." text
- [ ] "Is mining" column -> "Validator" -- new icon
- [ ] Total difficulty column
- [ ] Uncles column
- [ ] Rename "Up-time" column -> "Reporting stats"

**Comment by diminator** [comment]
I'm assuming we'd be forking `ethstats-server`?

For example the one of `goerli`:
https://github.com/goerli/ethstats-server/compare/master...diminator:diminator/celostats-%23464-remove-pow
