### ISSUE TITLE
Users SBAT see validator info in ethstats

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#465]
- [x] Add "Elected" as extra column to right of "Is mining"/"Validator" and populate with whether that validator is elected
- [x] Rename "Last Blocks Miner" to "Last Proposer" (field at top) -- and fix it -- it doesn't seem to work right now
- [ ] Read 'name' from Validator and group address (or even 'name' from Group)

**Comment by diminator** [comment]
"Last Blocks Miner" has been changed to "Recent Validators"
