### ISSUE TITLE
Ethstats SBAT support validator sentry setup 

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#482]

**Comment by diminator** [comment]
chatting w/ @kevjue and @mrsmkl about this:
- https://github.com/celo-org/celo-blockchain/pull/543 implements signed stats
- the signed stats are signed using the `nodeKey`, so the stats signer leaks the `enode` public key

Options:
- use a different key to sign stats (BLS)
- have the proxy sign stats with the proxy `nodeKey`, not the validator

**Comment by diminator** [comment]
After talking to @kevjue and @asaj it seems like we could use the `etherbase key` for signing the stats as this relates to the validator address and doesnt leak more sensitive info such as the enodetable.
