### ISSUE TITLE
Users SBAT query and see account info for HOGLers, Vs and VGs

### ISSUE THREAD

**Issue by diminator** [celo-org/celo-blockchain#521]
Add RPC API endpoints for celo-specific account information:
- [ ] Find (e.g. search for) an account using address and type 
- [ ] See account type: “Regular”, “Validator” or “Validator Group”
- [ ] See account cGLD and cUSD balance
- [ ] See amount of locked-up cGLD for account (this represents voting weight)

See design doc https://docs.google.com/document/d/12N5pH044vLXQxiGv3PpnvinUWBsq9jgIAjs7KTlgotY/

**Comment by cla-bel** [comment]
Betanet scope: no UI
