### ISSUE TITLE
Validators should select proposer according to an language independent shuffle

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#558]
### Expected Behavior

Validators should use the order of validators returned by the Election contract to determine the order for round robin proposer selection.

### Current Behavior

The random seed from the Random contract is used to seed a Golang implemented randomness source, which is used to create the permutation that is used.

**Comment by asaj** [comment]
Do we need to do this? What if we kept things as-is and stopped shuffling in `Election.sol`

**Comment by nategraf** [comment]
The origonal thought when opening this issue is that implementing the shuffle in the EVM will be more portable so it can be potentially adjusted in the future without hard fork and is kinder to any future non-Go implementations of the Celo node (as the current implementation uses the Golang specific random number generator). If we decide we don't care as much about ability to change the shuffle through governance, we can replace the Golang random number generator with something that could be reproduced in another language.

**Comment by nategraf** [comment]
It is currently unclear if we will be making this change based on further discussion.

**Comment by nategraf** [comment]
A step that will be simple to do now and well worth it in the long term is to make the shuffle independent of `math/rand`. Currently an update to that library would result in validators on different versions not being interoperable. This is a bad oversight, but should be easy to fix now. https://github.com/celo-org/celo-blockchain/blob/1c42b5fc115f0dfd58b8f72762098f0caf632ac5/consensus/istanbul/validator/selectors.go#L42
