### ISSUE TITLE
Missing error check in randomness commitment

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#567]
### Expected Behavior

We do something with the error on https://github.com/celo-org/celo-blockchain/blob/ba213df07070433970d9b2cf75bae1d146cbfeda/contract_comm/random/random.go#L172
### Current Behavior

We ignore the error, potentially committing a random value of zero.

**Comment by nategraf** [comment]
Fixed in https://github.com/celo-org/celo-blockchain/commit/1cf2aa6cfa9786ed1911b29361b9130f9fb7a0ad
