### ISSUE TITLE
Validators SBAT encrypt enodeURL field in announce message

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#569]
### Expected Behavior

Validators SBAT encrypt the enode URL field in the announce message using the receiving validators' public key.

If there are multiple enodes URLs (e.g. multiple sentries), then the validator should randomly choose one to encrypt for each receiving validator.

### Current Behavior

The enode URLs are sent in the clear.

**Comment by nategraf** [comment]
@kevjue was this fixed in the recent announce protocol work?

**Comment by kevjue** [comment]
> @kevjue was this fixed in the recent announce protocol work?

Yes
