### ISSUE TITLE
Repository should include a fork the the Ethereum tests repository

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#605]
### Expected Behavior

Ethereum has [a repository of implementation independent tests](https://github.com/ethereum/tests) which provides test coverage a certain amount of assurance that clients are interoperable. Celo should maintain a fork of those tests for use in improving test coverage and enabling developers to create other implementations in the future.

**Comment by mcortesi** [comment]
duplicate with #90
