### ISSUE TITLE
Proxied Validator SBAT immediately send updated val enode table to proxies when any table entry has changed.

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#606]
### Expected Behavior

Proxied Validator SBAT immediately send updated val enode table to proxies when any table entry has changed.

### Current Behavior

Currently, the proxied validator will send a copy of the val enode table once every 60 seconds, regardless of when the table is modified.

**Comment by nategraf** [comment]
@kevjue does the recent announce protocol work solve this issue?

**Comment by kevjue** [comment]
Yes.  I'll close it.
