### ISSUE TITLE
val enode table manager SNBAT explicitly manage validator connections

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#607]
### Expected Behavior

The management of the val enode table and the validator connections should be decoupled.  

To that end, @mcortesi  came up with a good idea in that there is a separate goroutine in the istanbul package that will take new announce/val_enode_share updates and will do the necessary changes to the val_enode_table and the validator connections.  This goroutine will also do periodic consistency checks between the val enode table and the validator connections.

### Current Behavior

The val_enode_table manager effectively manages the validator connections.

**Comment by nategraf** [comment]
@kevjue is this issue still relevant?

**Comment by kevjue** [comment]
> @kevjue is this issue still relevant?

Unfortunately yes.  Didn't get time to address this under the push to get RC1 done.
