### ISSUE TITLE
New validator can not be elected in Alfajores testnet due to out of gas

### ISSUE THREAD

**Issue by hqueue** [celo-org/celo-blockchain#631]
I'm using `us.gcr.io/celo-testnet/celo-node:alfajores` image to run a validator node.

## Expected Behavior

Validator set is updated at every epoch (every hour in Alfajores).

## Current Behavior
Looks like validator set is not updated from a day ago and use previous validator set when looking at below `geth` log.

Time is in `UTC`.
```
ERROR[11-20|15:02:14.676] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|16:05:02.349] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|17:06:38.245] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|18:08:41.235] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|19:11:28.765] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|20:16:18.257] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|21:18:46.236] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|22:22:50.261] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-20|23:26:49.263] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|00:29:24.240] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|01:36:51.579] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|02:47:45.238] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|03:53:00.283] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|05:00:15.243] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|06:05:58.745] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|07:10:34.814] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|08:17:08.733] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|09:21:20.632] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|10:27:23.320] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
ERROR[11-21|11:31:44.246] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
```

**Added after further investigation:**
I found it's due to `out of gas` while running below code.
https://github.com/celo-org/celo-blockchain/blob/223ab47bcbd24f0431a8df68291ffc459043e139/consensus/istanbul/backend/engine.go#L394-L401

Because i'm not sure which commit is used to build `geth` in docker image `us.gcr.io/celo-testnet/celo-node:alfajores`, I assume 223ab47bcbd24f0431a8df68291ffc459043e139.

`out of gas` occurs during invoking `getValidators` as below.

```
TRACE[11-21|14:45:38.004] Called UpdateValSetDiff                  number=448560 epoch=720
TRACE[11-21|14:45:38.004] createEVM called
TRACE[11-21|14:45:38.004] EVM call successful                      funcName=getAddressFor             transactionData=0xdd92723349dc7107d41d3c01a9f941a7d9a9f9177349b5521aeb56861470e42cf05da2ee                                                                                                                                 ret=0x000000000000000000000000cbe1d9b3d63b93897162ae248d45c5e13468877f
TRACE[11-21|14:45:38.004] createEVM called
TRACE[11-21|14:45:38.050] <-topicRegisterLookupTick
TRACE[11-21|14:45:38.050] <-net.queryReq
TRACE[11-21|14:45:38.050] <-topicRegisterLookupDone
TRACE[11-21|14:45:38.051] Found discovery topic to register        topic=LES2@92b2a5bbc9b1b519 target=4ea309…371480 delay=100ms
TRACE[11-21|14:45:38.151] <-topicRegisterLookupTick
TRACE[11-21|14:45:38.151] <-net.queryReq
TRACE[11-21|14:45:38.152] <-topicRegisterLookupDone
TRACE[11-21|14:45:38.152] Found discovery topic to register        topic=LES2@92b2a5bbc9b1b519 target=e9327e…c825a4 delay=100ms
DEBUG[11-21|14:45:38.228] UseGas failed due to insufficient gas    available gas=55 gas required=63
DEBUG[11-21|14:45:38.229] Run out of gas during execution          cost=63 err=nil                                         operation=MSTORE
ERROR[11-21|14:45:38.229] Error in calling the EVM                 funcName=getValidators             transactionData=0xb7ab4db5                                                                                                                                                                                                 err="evm: execution reverted"
ERROR[11-21|14:45:38.229] Error when invoking evm function         err="evm: execution reverted"
ERROR[11-21|14:45:38.229] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
```

And while executing below code, there are some smart contract static calls.

https://github.com/celo-org/celo-blockchain/blob/223ab47bcbd24f0431a8df68291ffc459043e139/consensus/istanbul/backend/engine.go#L398

For example, smart contract is  invoked at `GetElectedValidators` as below.
https://github.com/celo-org/celo-blockchain/blob/3ecd94a434f401179c5b16f4ccadff095401fc03/contract_comm/election/election.go#L121
And gas is given using below paremeters.
https://github.com/celo-org/celo-blockchain/blob/3ecd94a434f401179c5b16f4ccadff095401fc03/params/protocol_params.go#L160

Required gas may be increased as more validators are added to the contract.
Please take a look at this.

You can find code related to this issue in one diff by looking at https://github.com/hqueue/celo-blockchain/commit/e268c90eb18fde09f9a5e0dae51c59d271de965a. (however I can't identify exact commit of `geth` used for docker image yet.)

## Description
I've setup a validator node and sent Txs to run for election after locking cGLD.
Newly registered validator group (dsrvlabs) and validator (dsrvlabs) are listed in `celocli validatorgroup:list` and `celocli validator:list`.

```
$ celocli validatorgroup:list
Fetching Validator Groups... done
Address                                    Id                                Name                     Url                       Votes                 Members
0x3b4DdF54c6e87E1B81592c7Ae61a58484C5995c9 eyJ2ZXJzaW9uIjozLCJpZCI6IjNiZGMw… C-Labs                   https://www.celo.org      7.00001258e+23        70
...
0xaFC28608047d2e0F683e3ec29E74dA19EF15ea2e dsrvlabs                          dsrvlabs                 https://www.dsrvlabs.com  138380000000000000000 1
```

```
$ celocli validator:list
Fetching Validators... done
Address                                    Id Name                             Url                       Publickey Affiliation
0x456f41406B32c45D59E539e4BBA3D7898c3584dA 0… 0x456f41406B32c45D59E539e4BBA3D… https://www.celo.org      0xc26ee1… 0x3b4DdF54c6e87E1B81592c7Ae61a58484C5995c9
...
0x344aA30F72dB0d0faBE49d6a5d5c73e6971890a4 d… dsrvlabs                         https://www.dsrvlabs.com  0xbc3109… 0xaFC28608047d2e0F683e3ec29E74dA19EF15ea2e
```
However validator node is not included in the validator set until now and found above logs in the validator node.

Please take a look at this and let me know if this issue is my local issue or not.

**Comment by hqueue** [comment]
`out of gas` occurs during calling `getValidators` as below.

```
DEBUG[11-21|14:45:38.228] UseGas failed due to insufficient gas    available gas=55 gas required=63
DEBUG[11-21|14:45:38.229] Run out of gas during execution          cost=63 err=nil                                         operation=MSTORE
ERROR[11-21|14:45:38.229] Error in calling the EVM                 funcName=getValidators             transactionData=0xb7ab4db5                                                                                                                                                                                                 err="evm: execution reverted"
ERROR[11-21|14:45:38.229] Error when invoking evm function         err="evm: execution reverted"
ERROR[11-21|14:45:38.229] Istanbul.Finalize - Error in retrieving the validator set. Using the previous epoch's validator set err="evm: execution reverted"
```

`MaxGasForElectValidators` is defined as below.

https://github.com/celo-org/celo-blockchain/blob/3ecd94a434f401179c5b16f4ccadff095401fc03/params/protocol_params.go#L160

**Comment by nategraf** [comment]
First off, nice digging! Really impressive that you were able to track this down so quickly!

So `alfajores` validators are currently using commit `9575a01c12438e1adc6bb610c891cb5066aaa7aa`, which has max gas for getting the elected validators as `MaxGasForGetValidators uint64 = 10000000` (1 million) which is too low.

In https://github.com/celo-org/celo-blockchain/commit/8ca3de7d8784ce4d96e5bf4b588686b2292732db#diff-c3868eb970ebbbf00a0a47a656d12ce0R173 this was upped 50x, but this hasn't been deployed to `alfajores` yet. We were unaware that it was actively causing an issue.

We will be redeploying `alfajores` next week in the run-up to the The Great Celo Stakeoff and that should resolve the issue. (It is a hard-fork, so we are going to wait until the scheduled reset so we can get all the other changes in at the same time)

If you are not already planning on participating in the Stake Off we would really love to have your team join in the competition!

**Comment by hqueue** [comment]
> First off, nice digging! Really impressive that you were able to track this down so quickly!

It's no big deal, because we have experience in other blockchain projects using go-ethereum and Istanbul BFT before :)

> So alfajores validators are currently using commit 9575a01c12438e1adc6bb610c891cb5066aaa7aa, which has max gas for getting the elected validators as MaxGasForGetValidators uint64 = 10000000 (1 million) which is too low.

Got it, I was trying to figure this out

> In 8ca3de7#diff-c3868eb970ebbbf00a0a47a656d12ce0R173 this was upped 50x, but this hasn't been deployed to alfajores yet. We were unaware that it was actively causing an issue.
> We will be redeploying alfajores next week in the run-up to the The Great Celo Stakeoff and that should resolve the issue. (It is a hard-fork, so we are going to wait until the scheduled reset so we can get all the other changes in at the same time)

Thanks for the confirmation and looking forward for the fix next week.

> If you are not already planning on participating in the Stake Off we would really love to have your team join in the competition!

Of course, we are also interesting in the Stake Off and consider joining the competition.
