### ISSUE TITLE
Resubmit block proposal requests for istanbul

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#636]
### Expected Behavior

Within a sequence, the worker can send new requests to the istanbul consensus engine.  This will allow the new proposer to consider recent transactions that it synced.
 
### Current Behavior

Block request created at the beginning of a sequence, never changes until the next sequence (or mining stopped/restarted)

**Comment by nategraf** [comment]
@asaj @timmoreton can we get some more context on this? Is this something that needs to be solved ASAP?

**Comment by kevjue** [comment]
Going through old tickets, and wanted to mention that this should be thought through carefully.  E.g. there is a big safety reason that proposers in new rounds chose the highest prepare certificate's proposal, since it may already been committed by another validator.
