### ISSUE TITLE
Error: No proxy peers, cannot send Istanbul Validator Enodes Share message

### ISSUE THREAD

**Issue by daithi-coombes** [celo-org/celo-blockchain#690]
### Expected Behavior
Validator will connect to proxy and participate in consensus

### Current Behavior

Validator is not pariticipating in consensus (no rewards) and reporting:
```
No proxy peers, cannot send Istanbul Validator Enodes Share message
```

Proxy is reporting:
```
Failed to find the account $SEALER_ACCOUNT account url=
```

**Comment by hqueue** [comment]
Thanks @daithi-coombes 
I was opening the issue #691 to address the cause of this issue.

**Comment by daithi-coombes** [comment]
haha race condition in the stake off race lol.

Closing as duplicate of #691
