### ISSUE TITLE
Validator should be able to connect to proxy even when the proxy has max number of peers

### ISSUE THREAD

**Issue by hqueue** [celo-org/celo-blockchain#691]
Used following docker image for Baklava testnet.

```
$ docker images
REPOSITORY                         TAG                 IMAGE ID            CREATED             SIZE
us.gcr.io/celo-testnet/celo-node   baklava             2b47496301fa        40 hours ago        47.8MB
```

*ADDED*: This may be a root cause of #690 

### Expected Behavior
If a proxy is for a specific validator, the validator should be able to connect to proxy node even when a proxy node already has max number of peers. 

### Current Behavior
When proxy node has 75 peers as below.
```
# Proxy node
> net.peerCount
75
```
(looks like 75 is default max number of peers for geth in `us.gcr.io/celo-testnet/celo-node:baklava`) 

Validator removes a proxy peer with below `too many peers` error while conneting to proxy as below.
```
# log from validator
DEBUG[12-05|13:42:00.892] Removing p2p peer                        id=cbf5a9b6f55f388b conn=staticdial duration=2.182ms peers=0 req=true err="too many peers"
```

Consequently validator node cannot connect to Celo network and cannot participate in consensus.
```
# log from validator
ERROR[12-05|13:43:00.914] No proxy peers, cannot send Istanbul Validator Enodes Share message
```

### Workaround solution
1. Stop proxy node and validator node
2. Start validator node with `--proxy.proxyenodeurlpair` by follwing [Connect the Validator to the Proxy
](https://docs.celo.org/getting-started/baklava-testnet/running-a-validator#connect-the-validator-to-the-proxy)
3. Start proxy node with `--proxy.proxiedvalidatoraddress`  by following  [Deploy a proxy
](https://docs.celo.org/getting-started/baklava-testnet/running-a-validator#deploy-a-proxy)

In this way, validator node may connected to proxy node before proxy node has maximum number of peers.

**Comment by asaj** [comment]
Thanks @hqueue for reporting! It sounds like @kevjue has tracked this down. Once confirmed, a new docker image will be pushed. You will then be able to resolve the issue by pulling the new image and restarting your proxy

**Comment by kevjue** [comment]
@hqueue - Thanks again for letting us know of this issue!

We went ahead and merged in a bugfix into our Baklava branch and also just created and uploaded a new docker image.  Please go ahead and refetch your docker image and restart your proxy and validator.
