### ISSUE TITLE
When Consensus Engine is stopped; avoid processing or logging istanbul messages

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-blockchain#718]
When syncing, the consensus engine should be stopped. However, we still log the following messages:

```
ERROR[12-07|20:52:33.020] Failed to decode message from payload    address=0x6729622cB0535f168e744c4ecBc380fb230cB9b2 func=handleMsg         cur_seq=46275 cur_round=0 state="Waiting for new round" address=0x6729622cB0535f168e744c4ecBc380fb230cB9b2 err="unauthorized address"
```

```
WARN [12-07|20:52:07.318] Received an IstanbulAnnounce message from a non registered validator. Ignoring it. func=handleIstAnnounce msgAddress=0x09f4744faCE9d5e1b3FbCf264E77E4dcE70665Ed msg_round=0 msg_seq=64328 AnnounceMsg="{Code: 18, Address: 0x09f4744faCE9d5e1b3FbCf264E77E4dcE70665Ed}" err=nil
```

**Comment by asaj** [comment]
The former appears to be from the node itself, the latter from a validator that was registered after the block that we're currently synced to

**Comment by mcortesi** [comment]
I would like to do some initial digging here to understand a few things:

1. Can we me completely stop the consensus engine; so that no processing is done?
2. Why is it that consensus enginge is on, when we are syncing? Review the syncing vs consensus engine status lifecycle

**Comment by mcortesi** [comment]
@piersy something you can consider during your work on core
