### ISSUE TITLE
can not import account

### ISSUE THREAD

**Issue by wetezos** [celo-org/celo-blockchain#735]
### Expected Behavior
Excute commond:
 sudo docker run -v $PWD:/root/.celo -it $CELO_IMAGE account import /home/celo/bkup/account/UTC--2019-12-05T06-32-24.289805848Z--0537d935b50124b3bb9277d0356ce45400579c57

### Current Behavior
Have a error:
Fatal: Failed to load the private key: open /home/celo/bkup/account/: no such file or directory

But file path is correct:
ll /home/celo/bkup/account/UTC--2019-12-05T06-32-24.289805848Z--0537d935b50124b3bb9277d0356ce45400579c57
-rwxrwxrwx 1 root root 702 Dec  9 19:38 /home/celo/bkup/account/UTC--2019-12-05T06-32-24.289805848Z--0537d935b50124b3bb9277d0356ce45400579c57*

**Comment by mrsmkl** [comment]
You need to copy it inside the docker image, see for example https://docs.docker.com/engine/reference/commandline/cp/
