### ISSUE TITLE
Bad Block Freezing Validator

### ISSUE THREAD

**Issue by joesixpack** [celo-org/celo-blockchain#740]
########## BAD BLOCK #########                                                                                                               ?
?   Chain config: {ChainID: 12219 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0  Cons   ?
?   tantinopleFix: 0 Engine: istanbul}                                                                                                           ?
?   Number: 79552                                                                                                                                ?
?   Hash: 0xb26ca688d7400b71e2fa62919184fc27dc2f4ddee27c8708072fb993379dafec                                                                     ?
?   Error: evm: execution reverted                                                                                                               ?
?   ##############################                                                                                                               ?
?                                                                                                                                                ?
?   WARN [12-10|05:49:23.860] Header broke chain ordering              number=79555 hash=e42df1…03dc0f expected=79556                            ?
?   WARN [12-10|05:49:25.368] Synchronisation failed, dropping peer    peer=cad6a6c796743c85 err="action from bad peer ignored"                  ?
?   WARN [12-10|05:49:25.873] Delegate sign failed                     err="shutting down"                                                       ?
?   panic: runtime error: invalid memory address or nil pointer dereference                                                                      ?
?   [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb8b4db]                                                                       ?
?   goroutine 1269798 [running]:                                                                                                                 ?
?   github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).sendValEnodesShareMsg(0xc0000d6240, 0x2, 0x2)                          ?
?    /go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/consensus/istanbul/backend/val_enodes_share.go:167 +0x57b                 ?
?   created by github.com/ethereum/go-ethereum/consensus/istanbul/backend.(*Backend).sendValEnodesShareMsgs

**Comment by daithi-coombes** [comment]
@joesixpack do you know if you are using the `sgx driver` on your validator?

**Comment by joesixpack** [comment]
The CPU is too old to support the SGX enclave, so I would think not.

**Comment by daithi-coombes** [comment]
I wouldn't at the moment, afaik Celo isn't supporting `sgx` at the moment. We have been getting `bad blocks` on only our sgx machine's, so thats probably another reason not to

**Comment by nategraf** [comment]
@joesixpack Have you seen this again, or have any steps to help us reproduce it?

**Comment by joesixpack** [comment]
Have not seen it again.

**Comment by nategraf** [comment]
Ok, I am not sure how to reproduce this issue. It is most likely that the chain database become corrupt somehow, but it is unclear how. I am going to close out this issue and if the error is seen again, reopen it.
