### ISSUE TITLE
Validators SBAT use a push/pull gossip mechanism to distribute validator enode info

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#747]
### Expected Behavior

Validators SBAT use a push/pull gossip mechanism to to distribute validator enode info

### Current Behavior

Validators does a periodic push to send out its announce message.

This causes a few problem, specifically what to use as a nonce for each announce message.  Right now it's using the validator's local timestamp (https://github.com/celo-org/celo-blockchain/pull/745), but that causes a number of issues, since timestamp may go backwards in rare cases.

One other option is to have a validator keep a persisted counter for the announce message (basically similar to a tx nonce), but the problem there is if the validator loses that persisted counter from a disk malfunction, etc...., then that counter will also "go backwards".

The solution is for a validator to be able to pull its latest announce nonce on startup from other nodes' persistent disk (just like how an account's tx nonce can eventually be recovered).

**Comment by nategraf** [comment]
@kevjue was this fixed by the recent announce work?

**Comment by kevjue** [comment]
> @kevjue was this fixed by the recent announce work?

Yes
