### ISSUE TITLE
Removing static peer on ultralight client keeps peer static

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-blockchain#751]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

On an ultralight client (probably would happen with a normal light client as well, but I haven't tested):
1. `admin.addPeer(".....")`
2. Peer shows up with "ExplicitStaticPurpose"
3. `admin.removePeer(".....")`
4. Peer is disconnected, but soon is peered with again with "ExplicitStaticPurpose"

Logs when removing peer:
```
{"conn":"staticdial","err":"EOF","id":"8c2aa181e127b720405ad232085335ae16de5f08174e5b2beae2e8b80ee51194","msg":"Light Ethereum message handling failed","severity":"debug","timestamp":"2019-12-12T21:27:30.596089245Z"}
{"msg":"Removing Ethereum Light peer","peer":"8c2aa181e127b720","severity":"debug","timestamp":"2019-12-12T21:27:30.596202489Z"}
{"enode":"8c2aa181e127b720405ad232085335ae16de5f08174e5b2beae2e8b80ee51194","msg":"Disconnected old entry","severity":"debug","timestamp":"2019-12-12T21:27:30.596278454Z"}
{"conn":"staticdial","duration":"48.646s","err":"disconnect requested","id":"8c2aa181e127b720405ad232085335ae16de5f08174e5b2beae2e8b80ee51194","msg":"Removing p2p peer","peers":0,"req":"false","severity":"debug","timestamp":"2019-12-12T21:27:30.596354048Z"}
```

Then a bunch of logs similar to `{"err":"no suitable peers available","msg":"Failed to retrieve data from network","severity":"debug","timestamp":"2019-12-12T21:27:38.789643956Z"}`

And soon enough:

```
{"known":"true","lesaddr":"8c2aa181e127b720405ad232085335ae16de5f08174e5b2beae2e8b80ee51194@34.83.12.15:30303","msg":"Dialing new peer","set":1,"severity":"debug","timestamp":"2019-12-12T21:27:39.93890267Z"}
{"addr":"34.83.12.15:30303","msg":"Adding p2p peer","name":"Geth/v1.8.23-stable-...","peers":1,"severity":"debug","timestamp":"2019-12-12T21:27:39.946018517Z"}
{"enode":"8c2aa181e127b720","msg":"Connect new entry","severity":"debug","timestamp":"2019-12-12T21:27:39.946269944Z"}
{"conn":"staticdial","id":"8c2aa181e127b720405ad232085335ae16de5f08174e5b2beae2e8b80ee51194","msg":"Light Ethereum peer connected","name":"Geth/v1.8.23-stable-5d4224eb/linux-amd64/go1.11.13","severity":"debug","timestamp":"2019-12-12T21:27:39.946442363Z"}
```

**Comment by kevjue** [comment]
This looks like intended behavior.  The LES serverpool will attempt to redial known enodes: https://github.com/celo-org/celo-blockchain/blob/master/les/serverpool.go#L579

@mcortesi and I had a brief discussion in regards to his geth 1.9 work about creating a new purpose for this (e.g. LIGHT_CLIENT_PURPOSE).   But we decided against that as it will change the behavior in a subtle manner, even though it will make it more intuitive to the user.
