### ISSUE TITLE
Unable to get bootnodes on proxy

### ISSUE THREAD

**Issue by daithi-coombes** [celo-org/celo-blockchain#792]
### Expected Behavior

bootnodes will load from cdn

### Current Behavior

Returning error:
```
cat: can't open '/celo/bootnodes': No such file or directory
```

### Steps to Reproduce Behavior

Update docker image to latest, follow instructions and run:
```
export BOOTNODE_ENODES=`docker run --rm --entrypoint cat $CELO_IMAGE /celo/bootnodes`
```

### Logs
`ls -la /celo` of the image returns the following:

```
$ docker run --rm --entrypoint ls us.gcr.io/celo-testnet/celo-node:baklava -la /celo
total 52
drwxr-xr-x    1 root     root          4096 Jan  8 02:12 .
drwxr-xr-x    1 root     root          4096 Jan  8 07:57 ..
-rw-r--r--    1 root     root         40747 Jan  8 02:12 genesis.json
-rw-r--r--    1 root     root           792 Jan  8 02:12 static-nodes.json
```

### System information

Run `geth version`
```
Geth
Version: 1.8.23-stable
Architecture: amd64
Network Id: 1
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

**Comment by daithi-coombes** [comment]
noticing that `Network Id` is `1`, should this not be `121119`?

**Comment by tkporter** [comment]
Thanks for flagging! I'm going to close because it seems like it's been resolved.

Re: network id-- that should be fine. When starting a node the correct network id is passed but when running `geth version` it'll use the default, which will be changed once the mainnet network id is chosen.
