### ISSUE TITLE
Doc/scripts for rotating keys (zero-downtime upgrades)

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#794]
### Expected Behavior

Please describe the behavior you are expecting

### Current Behavior

What is the current behavior?

### Steps to Reproduce Behavior

How can we reproduce this?

### Logs

Are there any logs?

### System information

Run `geth version`

**Comment by nambrot** [comment]
Related to https://github.com/celo-org/celo-monorepo/issues/1762

**Comment by yorhodes** [comment]
example code here https://github.com/celo-org/celo-monorepo/blob/1d41d57da406940403f9c345e0a1233bbd9f5302/packages/celotool/src/e2e-tests/governance_tests.ts#L377
