### ISSUE TITLE
Speed up epoch block generation

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#795]

**Comment by nategraf** [comment]
Epoch block time difference is dominated by the running of `electValidatorSigners`. Other functions also require non-trivial amounts of time to run (50 - 200ms in the 80th percentile) but this one is by far the worst offender.

Here are some metrics gathered from C Labs Baklava validator #65 on January 27th.
```
    electValidatorSigners: {
      Avg01Min: "0 (0.00/s)",
      Avg05Min: "0 (0.00/s)",
      Avg15Min: "1 (0.00/s)",
      Maximum: "31.262607473s",
      Minimum: "36.999726ms",
      Overall: "832 (0.00/s)",
      Percentiles: {
        20: "549.400819ms",
        5: "414.219959ms",
        50: "930.51103ms",
        80: "5.013950966s",
        95: "14.296002472s"
      }
    },
```

Investigating ways to speed up this smart contract call could yield epoch block time improvements.

**Comment by oneeman** [comment]
See also https://github.com/celo-org/celo-blockchain/issues/919, which I'm closing in favor of this one as they are related.

**Comment by nategraf** [comment]
Note on this issue that the numbers cited above for the election function are out of date. The election function was later optimized to run much faster and it has not been profiled again recently. Recently work by @trianglesphere has shown that block validation, which includes running that function among other work, for Mainnet epoch blocks takes about 850 ms in the 50th percentile and 1300 ms in the 99th percentile.
