### ISSUE TITLE
Proxied validator stops syncing with proxy

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-blockchain#796]
### Expected Behavior

Validators do not fall out of sync with the proxy

### Current Behavior

C-labs validator 10 and another validator from Discord both saw this issue. The validator is elected, peered with its proxy who is synced with the rest of the network, is receiving consensus messages forwarded by the proxy, but the validator is stuck on a way lower block number. For validator 10 the validator is on block number `170853` but the proxy is synced at block `~350000` 

### Steps to Reproduce Behavior

Not sure :(

### Logs

n/a

### System information

Geth
Version: 1.8.23-stable
Git Commit: 600d14f60e5739beb8bc9d8545b925fd88876f6e
Architecture: amd64
Network Id: 1
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

**Comment by nategraf** [comment]
@tkporter could this be an early sighting of the issue addressed by https://github.com/celo-org/celo-blockchain/pull/840?

**Comment by tkporter** [comment]
Definitely, I'm going to close. Thanks!
