### ISSUE TITLE
[BUG] Unlocking Validator Accounts

### ISSUE THREAD

**Issue by joesixpack** [celo-org/celo-blockchain#806]
![image](https://user-images.githubusercontent.com/23145642/72287434-e7c91580-35fb-11ea-8b3f-1c9406d63bdd.png)

--account seems to have been deprecated and needs to be removed.

**Comment by nategraf** [comment]
Thanks for creating this issue! Sorry for the slow response, but it is not fixed https://docs.celo.org/getting-started/baklava-testnet/running-a-validator#register-the-accounts
