### ISSUE TITLE
Fix transaction failed to buy gas

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-blockchain#810]
Created issue from https://github.com/celo-org/celo-blockchain/pull/809#discussion_r366637087

So this is an error because if a transaction is being processed here, it is assumed that it was already validated by the transaction pool, in which case this should never happen. We are breaking that assumption in the `EstimateGas` function. I think the best way to handle this would be to run the transaction through transaction pool validation, either in its entirety or just to validate that the transaction can pay its fees, before applying the state transition.
Here is the `validateTx` function on `TxPool`, which you obviously can't call directly as it stands https://github.com/celo-org/celo-blockchain/blob/f86d6733274bb43377584cb9475a2fe46e17f368/core/tx_pool.go#L607
And here is the part that validates balances to ensure fees can be paid https://github.com/celo-org/celo-blockchain/blob/f86d6733274bb43377584cb9475a2fe46e17f368/core/tx_pool.go#L1201
Two courses of action would either be to export the former, or just call the latter if that turns out to be inappropriate. The call should probably occur here-ish https://github.com/celo-org/celo-blockchain/blob/f86d6733274bb43377584cb9475a2fe46e17f368/internal/ethapi/api.go#L740

If this seems onerous, please leave this log statement as is and copy the above into an issue to address later. And feel free to assign me to it.

**Comment by gastonponti** [comment]
Issue already fixed with the PR #825
