### ISSUE TITLE
Locked 10k and registered as Validator; Error accepting affiliation

### ISSUE THREAD

**Issue by dmichael** [celo-org/celo-blockchain#813]
### Expected Behavior

When locking up exactly 10000 cGLD and registering as a Validator, the registered account should be able to affiliate to a Validator Group without error.

### Current Behavior

Currently, the registered Validator account with exactly 10k locked cGLD fails acceptance into a group, even though the affiliate call works. When checking the balance, there is no longer 10k locked gold - its off by 1-e18

### Steps to Reproduce Behavior

* lock 10k cGLD
* register validator
* affiliate with a group
* have group attempt to accept
* 💥 

### Logs

Locked cGLD tx
https://baklava-blockscout.celo-testnet.org/tx/0x02fc5fa662cfcd601ae4beff197da4a311ca47e6f31271710e520bf757a7ba55/internal_transactions

### System information

The Validator had already been registered successfully and the affiliation tx went through successfully. 
Then this happened:
```
celocli validatorgroup:member --accept $CELO_VALIDATOR_ADDRESS --from $CELO_VALIDATOR_GROUP_ADDRESS
Running Checks:
   ✔  c5636b98fd6ddff3a7bb239e9729d75338e9a61f is Signer or registered Account
   ✔  Signer can sign Validator Txs
   ✔  Signer account is ValidatorGroup
   ✔  f1c7122d670b2bfd4dbc6accf6885b1844b07221 is Validator
Sending Transaction: addMember... !
Error: Returned error: gas required exceeds allowance or always failing transaction
    at Object.ErrorResponse (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-helpers/src/errors.js:29:16)
    at ~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-core-requestmanager/src/index.js:140:36
    at callbackDecorator (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/src/utils/eth-debug-provider.ts:16:7)
    at XMLHttpRequest.request.onreadystatechange (~/.nvm/versions/node/v10.17.0/lib/node_modules/@celo/celocli/node_modules/web3-providers-http/src/index.js:96:13)
```

Here is a snapshot of the situation from the registered Validator
```
celocli lockedgold:show f1c7122d670b2bfd4dbc6accf6885b1844b07221
Running Checks:
   ✔  f1c7122d670b2bfd4dbc6accf6885b1844b07221 is a registered Account
lockedGold:
  total: 9999999999999999999999 (~10000 10^18)
  nonvoting: 0
  requirement: 10000000000000000000000 (~10000 10^18)
pendingWithdrawals:
```

**Comment by pranaymohan** [comment]
Think this was due to the off by one rounding error that rounded down the 10k locked by one wei (see https://forum.celo.org/t/epoch-rewards-issue/498). This was fixed, so I think we can close this one out -- assuming you are no longer hitting this issue @dmichael?

**Comment by dmichael** [comment]
Thanks for following up. This can be closed, but we advise locking up 10001 to ensure its never an issue :)
