### ISSUE TITLE
Move `GetValidators` and `EpochSize` to Istanbul consensus specific interface

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#820]
### Expected Behavior

The methods `GetValidators` and `EpochSize` should be in the Istanbul consensus specific interface:  https://github.com/celo-org/celo-blockchain/blob/master/consensus/consensus.go#L168

### Current Behavior

They are currently in the "algorithm agnostic" consensus interface:  https://github.com/celo-org/celo-blockchain/blob/master/consensus/consensus.go#L56

### Steps to Reproduce Behavior

N/A

### Logs

N/A 

### System information

N/A

**Comment by ocotopdf** [comment]
Hey @kevjue

Looks like  the EVM `Context` for `contracts.go` is using the `Engine` interface.

Changing this context to Istanbul necessitates a refactor wherever the EVM context is used. Is that expected?

Thanks,
Erik

**Comment by kevjue** [comment]
Closing this issue, as it's not relevant anymore after this PR:  https://github.com/celo-org/celo-blockchain/pull/913.
