### ISSUE TITLE
Celo modifications to ethstats should be cleaner

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-blockchain#841]
### Expected Behavior

I didn't have the time to clean up this code, but we should.

### Current Behavior

Our modifications to the ethstats reporting aren't the cleanest and lead to a stall that was fixed in #840.

### Steps to Reproduce Behavior

How can we reproduce this?

### Logs

Are there any logs?

### System information

Run `geth version`

**Comment by gastonponti** [comment]
superseded by #1252
