### ISSUE TITLE
running geth from a shell script in docker makes it ignore docker kill command

### ISSUE THREAD

**Issue by AGx10k** [celo-org/celo-blockchain#857]
### Expected Behavior

Please describe the behavior you are expecting

`docker kill --signal=SIGINT celo-accounts`
this should gracefully stop `geth` like Ctrl-C does when started with `-it`

`docker stop` should send (by default if not stated otherwise while composing/building) SIGTERM which `geth` also treats as a graceful (see https://github.com/ethereum/go-ethereum/issues/16131#issuecomment-366916577 and https://github.com/ethereum/go-ethereum/pull/16142)

### Current Behavior

geth does not receive SIGINT/SIGTERM currently because started as a child of sh script -> leads to unclean shutdown and longer sync after restart of container

### Steps to Reproduce Behavior

`docker kill --SIGINT container`
`docker stop container`

### System information
Geth Version: 1.8.23-stable

### suggestion:
collect `geth` PID and send it INT/TERM/etc signals to the child. for example like this: https://unix.stackexchange.com/a/146770

**Comment by zviadm** [comment]
An easier solution would be to use:
`exec geth "$@"` in here: https://github.com/celo-org/celo-blockchain/blob/06788951cb2299f1af0c42c3126db28f9a62c044/scripts/run_geth_in_docker.sh#L11

That way there is no wrapper process left once it starts running

**Comment by zviadm** [comment]
Also my current work around is to use:
`docker exec <container name> pkill geth` 

instead of docker stop.

**Comment by AGx10k** [comment]
you possibly do not have `restart=always` or similar?

**Comment by zviadm** [comment]
> you possibly do not have `restart=always` or similar?

you have two options. one is:
`docker exec <container name> pkill geth && docker stop -t 0 <container name>`

it will do graceful stop and then immediatelly stop the container before it starts. 
A safer option:

`docker update --restart=no <container name> && docker exec <container name> pkill geth`

and you can set the `--restart=yes` before starting again

**Comment by AGx10k** [comment]
yeah i'm doing the second one also adding docker logs --tail 100 -f between all these to control the process

`docker update && kill -s INT PID (less convenient than pkill geth) && docker logs && do what i need (for example snapshot db to startup new machine) && docker update &&docker start && docker logs`

**Comment by AGx10k** [comment]
anyway all these are messy workarounds and docker stop should just work gracefully from the box, IMO

**Comment by nategraf** [comment]
Thanks for all the discussion! I've added `exec` to the script so that Geth is the only process in the container and will properly receive signals.
