### ISSUE TITLE
Receive a versioned enode/direct announce from any validator

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-blockchain#884]
### Expected Behavior

Any validator can directly send a versioned enode to another validator

### Current Behavior

With https://github.com/celo-org/celo-blockchain/pull/873, only a proxied validator can send the message to its proxy

**Comment by nategraf** [comment]
@tkporter wasn't this included in https://github.com/celo-org/celo-blockchain/pull/893

**Comment by tkporter** [comment]
Yes, I'll close
