### ISSUE TITLE
Internal re-audit of IBFT

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-blockchain#909]
Just diff since our last ToB audit and verify/audit that. Verify our fixes to ToB findings.

**Comment by timmoreton** [comment]
https://docs.google.com/document/d/1Cs_MuVz8mWTTDG1VZ5AIB-Kz82slmgxKkmJCYEhMT-Y/edit

**Comment by kevjue** [comment]
@trianglesphere - can this be closed?

**Comment by trianglesphere** [comment]
Yes. Only outstanding issues resolved in https://github.com/celo-org/celo-blockchain/pull/998. I found that all other issues were fixed or marked wontfix.
