### ISSUE TITLE
Finalize which hardforks will be included in the genesis block

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-blockchain#916]
### Expected Behavior

Related to https://github.com/celo-org/celo-blockchain/issues/901, we need to propose which hardforks from the ChainConfig we suggest be included in the genesis block.

**Comment by nategraf** [comment]
https://github.com/celo-org/celo-blockchain/blob/aa488e91b44fcbf78d62d9d212b4d71234684252/params/config.go#L298-L326

**Comment by mrsmkl** [comment]
Some info about these hardforks:
Homestead: changes to contract creation, ECDSA signatures
DAO fork: not really needed, this code could be removed
Eip 150: gas price changes (to fix shanghai love)
Eip 155: replay protection
Eip 158: clean up empty accounts
Byzantium: error handling, alt_bn128 support, variable length return values, STATICCALL
Constantinople + Petersburg: bitwise shifting, create2, extcodehash
Istanbul: gas cost changes, chainid opcode, blake2 compression function
eWASM: we probably don't want this right away?

So others will be needed except DAOFork (if we don't support other hardforks, solidity won't work). Istanbul is not needed right now, but should be probably be included later. It should not take much effort to support Istanbul hardfork, see https://github.com/celo-org/celo-monorepo/pull/3120.

**Comment by trianglesphere** [comment]
I've also summarized every hard fork I found [here](https://docs.google.com/document/d/19nJCawzzJuXCZ4uHpbWwWhyzSCMRRTBjBANet-E3B8o/edit?usp=sharing).

We are currently on **Constantinople + Petersberg**. The two hardforks in question are **Istanbul** and **the DAO**.

Istanbul: If it's easily added, it's likely worth doing given it's mainly EVM changes.
The DAO: I believe this is enabled by default without explicitly turning it off. I couldn't find anything saying that we're not on it.

Note on MuirGlacier: We don't even include the option to be on this hardfork, but given that all it does is change the ice age start time / change the difficulty calculation, I don't think it's needed.

**Comment by mrsmkl** [comment]
Yeah, DAO is probably turned on, but doesn't do anything...
About Istanbul, probably the most work would be to update our ganache. Also looks like there are some complications, at least the slashing tests are failing...

**Comment by AugustoL** [comment]
Is anyone working on this? Im interested in the support of Constantinople and petesburg to implement a CREATE2 wallet for celo.

**Comment by trianglesphere** [comment]
Hi @AugustoL we have included in the changes from constantinople and petersburg, and support those hardforks in our genesis. CREATE2 should be enabled, but if it doesn't work, please let us know.

The only EVM changes that we do not support at this time are the changes in the Istanbul hardfork.

**Comment by kevjue** [comment]
@nategraf - can this be closed?
