### ISSUE TITLE
Slow discovery

### ISSUE THREAD

**Issue by kevjue** [celo-org/celo-blockchain#929]
The testnets can take up to 30 minutes for the validators to peer with each other

**Comment by kevjue** [comment]
@jcortejoso observed that if the persisted discovery table (default location is at .celo/celo/nodes/) is deleted and the node restarted, then the node will then be able to discover other nodes in the network.

**Comment by oneeman** [comment]
The mention of 30 minutes specifically makes me think this is due to the two bugs fixed in #1194
