### ISSUE TITLE
Missing documentation on configuration parameters to run geth

### ISSUE THREAD

**Issue by astudnev** [celo-org/celo-blockchain#933]
Please point to proper configuration ( not Docker ! ) of the network to run geth node for Baklava and Alfajores.

I built sources from https://github.com/celo-org/celo-blockchain and what i need is what parameters need to submit to geth command to run full node.

**Comment by hbandura** [comment]
The docker image forwards the command line arguments to the geth binary, so using the same parameters without the docker ones will work. However I believe docker is currently the preferred method of running it.


This are the command line parameters sent to the geth binary in the documentation:

`--verbosity 3 --syncmode full --rpc --rpcaddr 0.0.0.0 --rpcapi eth,net,web3,debug,admin,personal --light.serve 90 --light.maxpeers 1000 --maxpeers 1100 --etherbase $CELO_ACCOUNT_ADDRESS --nousb --baklava --datadir /root/.celo`

The `--baklava` argument states to use the baklava network genesis block and network. `--alfajores` will do the equivalent.
