### ISSUE TITLE
 Code coverage is not generated and therefore not reported to codecov

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-blockchain#935]
### Expected Behavior

Code coverage is being generated and reported to codecov

### Current Behavior

Code coverage is not generated and therefore not reported to codecov.

As seen here codecov fails because it cannot find the code coverage.  Also it is not possible to generate code coverage locally. It is just not being generated when running `TEST_FLAGS=-coverage make test` it will only show the percentage in the stdout. 

https://circleci.com/gh/celo-org/celo-blockchain/28201?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
#!/bin/bash -eo pipefail
bash <(curl -s https://codecov.io/bash)

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-tbd


==> Circle CI detected.
    project root: .
--> token set from env
    Yaml found at: .codecov.yml
==> Running gcov in . (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + .
--> No coverage report found.
    Please visit http://docs.codecov.io/docs/supported-languages
```

**Comment by piersy** [comment]
This has been done
