### ISSUE TITLE
Remove support for EIP155

### ISSUE THREAD

**Issue by kobigurk** [celo-org/celo-blockchain#972]
[EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) is used to provide simple replay protection by additionally signing the chain ID with the transaction.

It's useful when the same private key is used in multiple chains, so that transactions can't be replayed in other chains.

Currently, celo-blockchain supports both "old style" transactions that don't include the chain ID and EIP155 transactions.

Ideally, we could remove it and thus gain protection for people copying private keys and more importantly for people using the same key for a testnet and mainnet.

@gakonst made some really good points why it might be problematic to remove it:
* Current tools (JS, most probably) might not sign using EIP155.
* Smart contracts might not support validating EIP155 transactions, especially if it's true that the corresponding JS libraries don't support EIP155.

**Comment by gakonst** [comment]
Zeppelin doesn't seem to be using EIP-155 for example: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol#L57-L59

**Comment by kobigurk** [comment]
> Zeppelin doesn't seem to be using EIP-155 for example: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/cryptography/ECDSA.sol#L57-L59 (closed issue: [OpenZeppelin/openzeppelin-contracts#2108](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2108))

Ah, that's only for "personal signing" though, which is not the prime use-case for EIP-155. I think that smart contract only ever run ecrecover on this personally signed messages, so we should probably be worried about transactions rather than personal signing.

I hope we change the prefix in personal signing anyway.

**Comment by kobigurk** [comment]
@gakonst we don't use EIP-155 for personal messages anyway.

**Comment by mcortesi** [comment]
I don't follow entirely @kobigurk .

 * Why would we want to remove EIP155 replay protection? 
 * How is that removing it will " gain (us) protection for people copying private keys and more importantly for people using the same key for a testnet and mainnet"?

**Comment by mcortesi** [comment]
Currently, EIP155 is actually enforced, as a way to enforce replay protection. This happened during Donut HF. If we want to raise this again, or even allow tx without replay protection let's discuss this in a new issue
