### ISSUE TITLE
Lower logging verbosity of "encrypting enodeURL"

### ISSUE THREAD

**Issue by tkporter** [celo-org/celo-blockchain#976]
### Expected Behavior

https://github.com/celo-org/celo-blockchain/blob/master/consensus/istanbul/backend/announce.go#L529 should be `debug` or `trace`

### Current Behavior

https://github.com/celo-org/celo-blockchain/blob/master/consensus/istanbul/backend/announce.go#L529 is `info`, which is high

### Steps to Reproduce Behavior

How can we reproduce this?

### Logs

Are there any logs?

### System information

Run `geth version`

**Comment by mcortesi** [comment]
current line https://github.com/celo-org/celo-blockchain/blob/master/consensus/istanbul/backend/announce.go#L625
